// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: trip.proto

package trip

import (
	common "github.com/ishakdeveloper/surge/shared/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TripStatus is the state machine, and the wire is the place it is written
// down once. UNSPECIFIED is reserved by convention so an unset field is not
// silently a valid state.
type TripStatus int32

const (
	TripStatus_TRIP_STATUS_UNSPECIFIED TripStatus = 0
	TripStatus_TRIP_STATUS_REQUESTED   TripStatus = 1
	TripStatus_TRIP_STATUS_OFFERED     TripStatus = 2
	TripStatus_TRIP_STATUS_ACCEPTED    TripStatus = 3
	TripStatus_TRIP_STATUS_ARRIVED     TripStatus = 4
	TripStatus_TRIP_STATUS_IN_PROGRESS TripStatus = 5
	TripStatus_TRIP_STATUS_COMPLETED   TripStatus = 6
	TripStatus_TRIP_STATUS_CANCELLED   TripStatus = 7
	// No driver was found before the request expired. Distinct from cancelled:
	// nobody chose it, and the rider should be offered a retry rather than an
	// apology.
	TripStatus_TRIP_STATUS_UNMATCHED TripStatus = 8
)

// Enum value maps for TripStatus.
var (
	TripStatus_name = map[int32]string{
		0: "TRIP_STATUS_UNSPECIFIED",
		1: "TRIP_STATUS_REQUESTED",
		2: "TRIP_STATUS_OFFERED",
		3: "TRIP_STATUS_ACCEPTED",
		4: "TRIP_STATUS_ARRIVED",
		5: "TRIP_STATUS_IN_PROGRESS",
		6: "TRIP_STATUS_COMPLETED",
		7: "TRIP_STATUS_CANCELLED",
		8: "TRIP_STATUS_UNMATCHED",
	}
	TripStatus_value = map[string]int32{
		"TRIP_STATUS_UNSPECIFIED": 0,
		"TRIP_STATUS_REQUESTED":   1,
		"TRIP_STATUS_OFFERED":     2,
		"TRIP_STATUS_ACCEPTED":    3,
		"TRIP_STATUS_ARRIVED":     4,
		"TRIP_STATUS_IN_PROGRESS": 5,
		"TRIP_STATUS_COMPLETED":   6,
		"TRIP_STATUS_CANCELLED":   7,
		"TRIP_STATUS_UNMATCHED":   8,
	}
)

func (x TripStatus) Enum() *TripStatus {
	p := new(TripStatus)
	*p = x
	return p
}

func (x TripStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trip_proto_enumTypes[0].Descriptor()
}

func (TripStatus) Type() protoreflect.EnumType {
	return &file_trip_proto_enumTypes[0]
}

func (x TripStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TripStatus.Descriptor instead.
func (TripStatus) EnumDescriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{0}
}

// The caller is NOT a field on any request.
//
// It arrives as gRPC metadata, put there by the gateway from a verified token.
// This matters more now that the REST body maps straight onto the message: a
// `rider_id` field would be client-supplied, and a client that can name the
// rider can quote, book and read rides as somebody else.
type PreviewTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickup        *common.Coordinate     `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *common.Coordinate     `protobuf:"bytes,2,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripRequest) Reset() {
	*x = PreviewTripRequest{}
	mi := &file_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripRequest) ProtoMessage() {}

func (x *PreviewTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripRequest.ProtoReflect.Descriptor instead.
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewTripRequest) GetPickup() *common.Coordinate {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *PreviewTripRequest) GetDropoff() *common.Coordinate {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

type PreviewTripResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quotes for each vehicle class, priced from the same route.
	Fares         []*FareQuote  `protobuf:"bytes,1,rep,name=fares,proto3" json:"fares,omitempty"`
	Route         *common.Route `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripResponse) Reset() {
	*x = PreviewTripResponse{}
	mi := &file_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripResponse) ProtoMessage() {}

func (x *PreviewTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripResponse.ProtoReflect.Descriptor instead.
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewTripResponse) GetFares() []*FareQuote {
	if x != nil {
		return x.Fares
	}
	return nil
}

func (x *PreviewTripResponse) GetRoute() *common.Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type FareQuote struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FareId string                 `protobuf:"bytes,1,opt,name=fare_id,json=fareId,proto3" json:"fare_id,omitempty"`
	// Sedan, van and so on. A string rather than an enum because the catalogue is
	// operator configuration, not a protocol change.
	PackageSlug string `protobuf:"bytes,2,opt,name=package_slug,json=packageSlug,proto3" json:"package_slug,omitempty"`
	TotalCents  int64  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	// The multiplier applied for demand in the pickup cell at quote time. Carried
	// explicitly so a rider can be shown why a fare is what it is.
	SurgeMultiplier float64                `protobuf:"fixed64,4,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FareQuote) Reset() {
	*x = FareQuote{}
	mi := &file_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareQuote) ProtoMessage() {}

func (x *FareQuote) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareQuote.ProtoReflect.Descriptor instead.
func (*FareQuote) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{2}
}

func (x *FareQuote) GetFareId() string {
	if x != nil {
		return x.FareId
	}
	return ""
}

func (x *FareQuote) GetPackageSlug() string {
	if x != nil {
		return x.PackageSlug
	}
	return ""
}

func (x *FareQuote) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *FareQuote) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *FareQuote) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateTripRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FareId string                 `protobuf:"bytes,1,opt,name=fare_id,json=fareId,proto3" json:"fare_id,omitempty"`
	// Generated client-side, so a retry over a flaky connection is recognised
	// rather than booked twice. Over REST this also arrives as an
	// `Idempotency-Key` header, which the gateway copies into the field.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTripRequest) GetFareId() string {
	if x != nil {
		return x.FareId
	}
	return ""
}

func (x *CreateTripRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5}
}

func (x *GetTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripResponse) Reset() {
	*x = GetTripResponse{}
	mi := &file_trip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripResponse) ProtoMessage() {}

func (x *GetTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripResponse.ProtoReflect.Descriptor instead.
func (*GetTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6}
}

func (x *GetTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type CancelTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTripRequest) Reset() {
	*x = CancelTripRequest{}
	mi := &file_trip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTripRequest) ProtoMessage() {}

func (x *CancelTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTripRequest.ProtoReflect.Descriptor instead.
func (*CancelTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CancelTripRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTripResponse) Reset() {
	*x = CancelTripResponse{}
	mi := &file_trip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTripResponse) ProtoMessage() {}

func (x *CancelTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTripResponse.ProtoReflect.Descriptor instead.
func (*CancelTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type ListTripsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size. Clamped by the server; a client asking for everything gets a
	// page, because "return the whole table" is not a request a public API
	// should honour.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor from a previous response. Opaque on purpose: a client that
	// decodes it is a client that breaks when the ordering changes.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional status filter, e.g. "completed".
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTripsRequest) Reset() {
	*x = ListTripsRequest{}
	mi := &file_trip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsRequest) ProtoMessage() {}

func (x *ListTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsRequest.ProtoReflect.Descriptor instead.
func (*ListTripsRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9}
}

func (x *ListTripsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTripsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTripsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTripsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Trips []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	// Empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTripsResponse) Reset() {
	*x = ListTripsResponse{}
	mi := &file_trip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsResponse) ProtoMessage() {}

func (x *ListTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsResponse.ProtoReflect.Descriptor instead.
func (*ListTripsResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10}
}

func (x *ListTripsResponse) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *ListTripsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        TripStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=surge.trip.v1.TripStatus" json:"status,omitempty"`
	Pickup        *common.Coordinate     `protobuf:"bytes,5,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *common.Coordinate     `protobuf:"bytes,6,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Route         *common.Route          `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
	TotalCents    int64                  `protobuf:"varint,8,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_trip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Trip) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Trip) GetStatus() TripStatus {
	if x != nil {
		return x.Status
	}
	return TripStatus_TRIP_STATUS_UNSPECIFIED
}

func (x *Trip) GetPickup() *common.Coordinate {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *Trip) GetDropoff() *common.Coordinate {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *Trip) GetRoute() *common.Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *Trip) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Trip) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Trip) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_trip_proto protoreflect.FileDescriptor

const file_trip_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trip.proto\x12\rsurge.trip.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\x80\x01\n" +
	"\x12PreviewTripRequest\x123\n" +
	"\x06pickup\x18\x01 \x01(\v2\x1b.surge.common.v1.CoordinateR\x06pickup\x125\n" +
	"\adropoff\x18\x02 \x01(\v2\x1b.surge.common.v1.CoordinateR\adropoff\"s\n" +
	"\x13PreviewTripResponse\x12.\n" +
	"\x05fares\x18\x01 \x03(\v2\x18.surge.trip.v1.FareQuoteR\x05fares\x12,\n" +
	"\x05route\x18\x02 \x01(\v2\x16.surge.common.v1.RouteR\x05route\"\xce\x01\n" +
	"\tFareQuote\x12\x17\n" +
	"\afare_id\x18\x01 \x01(\tR\x06fareId\x12!\n" +
	"\fpackage_slug\x18\x02 \x01(\tR\vpackageSlug\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\x12)\n" +
	"\x10surge_multiplier\x18\x04 \x01(\x01R\x0fsurgeMultiplier\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"U\n" +
	"\x11CreateTripRequest\x12\x17\n" +
	"\afare_id\x18\x01 \x01(\tR\x06fareId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"=\n" +
	"\x12CreateTripResponse\x12'\n" +
	"\x04trip\x18\x01 \x01(\v2\x13.surge.trip.v1.TripR\x04trip\")\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\":\n" +
	"\x0fGetTripResponse\x12'\n" +
	"\x04trip\x18\x01 \x01(\v2\x13.surge.trip.v1.TripR\x04trip\"D\n" +
	"\x11CancelTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\x12CancelTripResponse\x12'\n" +
	"\x04trip\x18\x01 \x01(\v2\x13.surge.trip.v1.TripR\x04trip\"f\n" +
	"\x10ListTripsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"f\n" +
	"\x11ListTripsResponse\x12)\n" +
	"\x05trips\x18\x01 \x03(\v2\x13.surge.trip.v1.TripR\x05trips\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb2\x03\n" +
	"\x04Trip\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.surge.trip.v1.TripStatusR\x06status\x123\n" +
	"\x06pickup\x18\x05 \x01(\v2\x1b.surge.common.v1.CoordinateR\x06pickup\x125\n" +
	"\adropoff\x18\x06 \x01(\v2\x1b.surge.common.v1.CoordinateR\adropoff\x12,\n" +
	"\x05route\x18\a \x01(\v2\x16.surge.common.v1.RouteR\x05route\x12\x1f\n" +
	"\vtotal_cents\x18\b \x01(\x03R\n" +
	"totalCents\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xfe\x01\n" +
	"\n" +
	"TripStatus\x12\x1b\n" +
	"\x17TRIP_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRIP_STATUS_REQUESTED\x10\x01\x12\x17\n" +
	"\x13TRIP_STATUS_OFFERED\x10\x02\x12\x18\n" +
	"\x14TRIP_STATUS_ACCEPTED\x10\x03\x12\x17\n" +
	"\x13TRIP_STATUS_ARRIVED\x10\x04\x12\x1b\n" +
	"\x17TRIP_STATUS_IN_PROGRESS\x10\x05\x12\x19\n" +
	"\x15TRIP_STATUS_COMPLETED\x10\x06\x12\x19\n" +
	"\x15TRIP_STATUS_CANCELLED\x10\a\x12\x19\n" +
	"\x15TRIP_STATUS_UNMATCHED\x10\b2\xae\x04\n" +
	"\vTripService\x12r\n" +
	"\vPreviewTrip\x12!.surge.trip.v1.PreviewTripRequest\x1a\".surge.trip.v1.PreviewTripResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/trips:preview\x12g\n" +
	"\n" +
	"CreateTrip\x12 .surge.trip.v1.CreateTripRequest\x1a!.surge.trip.v1.CreateTripResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/trips\x12e\n" +
	"\aGetTrip\x12\x1d.surge.trip.v1.GetTripRequest\x1a\x1e.surge.trip.v1.GetTripResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/trips/{trip_id}\x12x\n" +
	"\n" +
	"CancelTrip\x12 .surge.trip.v1.CancelTripRequest\x1a!.surge.trip.v1.CancelTripResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/trips/{trip_id}:cancel\x12a\n" +
	"\tListTrips\x12\x1f.surge.trip.v1.ListTripsRequest\x1a .surge.trip.v1.ListTripsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tripsB8Z6github.com/ishakdeveloper/surge/shared/proto/trip;tripb\x06proto3"

var (
	file_trip_proto_rawDescOnce sync.Once
	file_trip_proto_rawDescData []byte
)

func file_trip_proto_rawDescGZIP() []byte {
	file_trip_proto_rawDescOnce.Do(func() {
		file_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)))
	})
	return file_trip_proto_rawDescData
}

var file_trip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_trip_proto_goTypes = []any{
	(TripStatus)(0),               // 0: surge.trip.v1.TripStatus
	(*PreviewTripRequest)(nil),    // 1: surge.trip.v1.PreviewTripRequest
	(*PreviewTripResponse)(nil),   // 2: surge.trip.v1.PreviewTripResponse
	(*FareQuote)(nil),             // 3: surge.trip.v1.FareQuote
	(*CreateTripRequest)(nil),     // 4: surge.trip.v1.CreateTripRequest
	(*CreateTripResponse)(nil),    // 5: surge.trip.v1.CreateTripResponse
	(*GetTripRequest)(nil),        // 6: surge.trip.v1.GetTripRequest
	(*GetTripResponse)(nil),       // 7: surge.trip.v1.GetTripResponse
	(*CancelTripRequest)(nil),     // 8: surge.trip.v1.CancelTripRequest
	(*CancelTripResponse)(nil),    // 9: surge.trip.v1.CancelTripResponse
	(*ListTripsRequest)(nil),      // 10: surge.trip.v1.ListTripsRequest
	(*ListTripsResponse)(nil),     // 11: surge.trip.v1.ListTripsResponse
	(*Trip)(nil),                  // 12: surge.trip.v1.Trip
	(*common.Coordinate)(nil),     // 13: surge.common.v1.Coordinate
	(*common.Route)(nil),          // 14: surge.common.v1.Route
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_trip_proto_depIdxs = []int32{
	13, // 0: surge.trip.v1.PreviewTripRequest.pickup:type_name -> surge.common.v1.Coordinate
	13, // 1: surge.trip.v1.PreviewTripRequest.dropoff:type_name -> surge.common.v1.Coordinate
	3,  // 2: surge.trip.v1.PreviewTripResponse.fares:type_name -> surge.trip.v1.FareQuote
	14, // 3: surge.trip.v1.PreviewTripResponse.route:type_name -> surge.common.v1.Route
	15, // 4: surge.trip.v1.FareQuote.expires_at:type_name -> google.protobuf.Timestamp
	12, // 5: surge.trip.v1.CreateTripResponse.trip:type_name -> surge.trip.v1.Trip
	12, // 6: surge.trip.v1.GetTripResponse.trip:type_name -> surge.trip.v1.Trip
	12, // 7: surge.trip.v1.CancelTripResponse.trip:type_name -> surge.trip.v1.Trip
	12, // 8: surge.trip.v1.ListTripsResponse.trips:type_name -> surge.trip.v1.Trip
	0,  // 9: surge.trip.v1.Trip.status:type_name -> surge.trip.v1.TripStatus
	13, // 10: surge.trip.v1.Trip.pickup:type_name -> surge.common.v1.Coordinate
	13, // 11: surge.trip.v1.Trip.dropoff:type_name -> surge.common.v1.Coordinate
	14, // 12: surge.trip.v1.Trip.route:type_name -> surge.common.v1.Route
	15, // 13: surge.trip.v1.Trip.created_at:type_name -> google.protobuf.Timestamp
	15, // 14: surge.trip.v1.Trip.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 15: surge.trip.v1.TripService.PreviewTrip:input_type -> surge.trip.v1.PreviewTripRequest
	4,  // 16: surge.trip.v1.TripService.CreateTrip:input_type -> surge.trip.v1.CreateTripRequest
	6,  // 17: surge.trip.v1.TripService.GetTrip:input_type -> surge.trip.v1.GetTripRequest
	8,  // 18: surge.trip.v1.TripService.CancelTrip:input_type -> surge.trip.v1.CancelTripRequest
	10, // 19: surge.trip.v1.TripService.ListTrips:input_type -> surge.trip.v1.ListTripsRequest
	2,  // 20: surge.trip.v1.TripService.PreviewTrip:output_type -> surge.trip.v1.PreviewTripResponse
	5,  // 21: surge.trip.v1.TripService.CreateTrip:output_type -> surge.trip.v1.CreateTripResponse
	7,  // 22: surge.trip.v1.TripService.GetTrip:output_type -> surge.trip.v1.GetTripResponse
	9,  // 23: surge.trip.v1.TripService.CancelTrip:output_type -> surge.trip.v1.CancelTripResponse
	11, // 24: surge.trip.v1.TripService.ListTrips:output_type -> surge.trip.v1.ListTripsResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_trip_proto_init() }
func file_trip_proto_init() {
	if File_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trip_proto_goTypes,
		DependencyIndexes: file_trip_proto_depIdxs,
		EnumInfos:         file_trip_proto_enumTypes,
		MessageInfos:      file_trip_proto_msgTypes,
	}.Build()
	File_trip_proto = out.File
	file_trip_proto_goTypes = nil
	file_trip_proto_depIdxs = nil
}
