/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifiedRouteImport } from './routes/auth/verified'
import { Route as ProtectedConsoleIndexRouteImport } from './routes/_protected/console/index'
import { Route as ProtectedDriveIndexRouteImport } from './routes/_protected/drive/index'
import { Route as ProtectedDriveEarningsRouteImport } from './routes/_protected/drive/earnings'
import { Route as ProtectedRideIndexRouteImport } from './routes/_protected/ride/index'
import { Route as ProtectedRidePaymentRouteImport } from './routes/_protected/ride/payment'
import { Route as ProtectedDrivePayoutsRefreshRouteImport } from './routes/_protected/drive/payouts/refresh'
import { Route as ProtectedDrivePayoutsReturnRouteImport } from './routes/_protected/drive/payouts/return'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedConsoleIndexRoute = ProtectedConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriveIndexRoute = ProtectedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriveEarningsRoute = ProtectedDriveEarningsRouteImport.update({
  id: '/drive/earnings',
  path: '/drive/earnings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRideIndexRoute = ProtectedRideIndexRouteImport.update({
  id: '/ride/',
  path: '/ride/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRidePaymentRoute = ProtectedRidePaymentRouteImport.update({
  id: '/ride/payment',
  path: '/ride/payment',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDrivePayoutsRefreshRoute =
  ProtectedDrivePayoutsRefreshRouteImport.update({
    id: '/drive/payouts/refresh',
    path: '/drive/payouts/refresh',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDrivePayoutsReturnRoute =
  ProtectedDrivePayoutsReturnRouteImport.update({
    id: '/drive/payouts/return',
    path: '/drive/payouts/return',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/ride/payment': typeof ProtectedRidePaymentRoute
  '/console/': typeof ProtectedConsoleIndexRoute
  '/drive/': typeof ProtectedDriveIndexRoute
  '/ride/': typeof ProtectedRideIndexRoute
  '/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/': typeof ProtectedIndexRoute
  '/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/ride/payment': typeof ProtectedRidePaymentRoute
  '/console': typeof ProtectedConsoleIndexRoute
  '/drive': typeof ProtectedDriveIndexRoute
  '/ride': typeof ProtectedRideIndexRoute
  '/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/_protected/ride/payment': typeof ProtectedRidePaymentRoute
  '/_protected/console/': typeof ProtectedConsoleIndexRoute
  '/_protected/drive/': typeof ProtectedDriveIndexRoute
  '/_protected/ride/': typeof ProtectedRideIndexRoute
  '/_protected/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/_protected/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/drive/earnings'
    | '/ride/payment'
    | '/console/'
    | '/drive/'
    | '/ride/'
    | '/drive/payouts/refresh'
    | '/drive/payouts/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/'
    | '/drive/earnings'
    | '/ride/payment'
    | '/console'
    | '/drive'
    | '/ride'
    | '/drive/payouts/refresh'
    | '/drive/payouts/return'
  id:
    | '__root__'
    | '/auth'
    | '/_protected'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/_protected/'
    | '/_protected/drive/earnings'
    | '/_protected/ride/payment'
    | '/_protected/console/'
    | '/_protected/drive/'
    | '/_protected/ride/'
    | '/_protected/drive/payouts/refresh'
    | '/_protected/drive/payouts/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/console/': {
      id: '/_protected/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ProtectedConsoleIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/': {
      id: '/_protected/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof ProtectedDriveIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/earnings': {
      id: '/_protected/drive/earnings'
      path: '/drive/earnings'
      fullPath: '/drive/earnings'
      preLoaderRoute: typeof ProtectedDriveEarningsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ride/': {
      id: '/_protected/ride/'
      path: '/ride'
      fullPath: '/ride/'
      preLoaderRoute: typeof ProtectedRideIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ride/payment': {
      id: '/_protected/ride/payment'
      path: '/ride/payment'
      fullPath: '/ride/payment'
      preLoaderRoute: typeof ProtectedRidePaymentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/payouts/refresh': {
      id: '/_protected/drive/payouts/refresh'
      path: '/drive/payouts/refresh'
      fullPath: '/drive/payouts/refresh'
      preLoaderRoute: typeof ProtectedDrivePayoutsRefreshRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/payouts/return': {
      id: '/_protected/drive/payouts/return'
      path: '/drive/payouts/return'
      fullPath: '/drive/payouts/return'
      preLoaderRoute: typeof ProtectedDrivePayoutsReturnRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDriveEarningsRoute: typeof ProtectedDriveEarningsRoute
  ProtectedRidePaymentRoute: typeof ProtectedRidePaymentRoute
  ProtectedConsoleIndexRoute: typeof ProtectedConsoleIndexRoute
  ProtectedDriveIndexRoute: typeof ProtectedDriveIndexRoute
  ProtectedRideIndexRoute: typeof ProtectedRideIndexRoute
  ProtectedDrivePayoutsRefreshRoute: typeof ProtectedDrivePayoutsRefreshRoute
  ProtectedDrivePayoutsReturnRoute: typeof ProtectedDrivePayoutsReturnRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDriveEarningsRoute: ProtectedDriveEarningsRoute,
  ProtectedRidePaymentRoute: ProtectedRidePaymentRoute,
  ProtectedConsoleIndexRoute: ProtectedConsoleIndexRoute,
  ProtectedDriveIndexRoute: ProtectedDriveIndexRoute,
  ProtectedRideIndexRoute: ProtectedRideIndexRoute,
  ProtectedDrivePayoutsRefreshRoute: ProtectedDrivePayoutsRefreshRoute,
  ProtectedDrivePayoutsReturnRoute: ProtectedDrivePayoutsReturnRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
