/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProtectedConsoleIndexRouteImport } from './routes/_protected/console/index'
import { Route as ProtectedDriveIndexRouteImport } from './routes/_protected/drive/index'
import { Route as ProtectedDriveEarningsRouteImport } from './routes/_protected/drive/earnings'
import { Route as ProtectedMessagesIndexRouteImport } from './routes/_protected/messages/index'
import { Route as ProtectedMessagesConversationIdRouteImport } from './routes/_protected/messages/$conversationId'
import { Route as ProtectedMessagesNewRouteImport } from './routes/_protected/messages/new'
import { Route as ProtectedRideIndexRouteImport } from './routes/_protected/ride/index'
import { Route as ProtectedRidePaymentRouteImport } from './routes/_protected/ride/payment'
import { Route as ProtectedSupportIndexRouteImport } from './routes/_protected/support/index'
import { Route as ProtectedDrivePayoutsRefreshRouteImport } from './routes/_protected/drive/payouts/refresh'
import { Route as ProtectedDrivePayoutsReturnRouteImport } from './routes/_protected/drive/payouts/return'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedConsoleIndexRoute = ProtectedConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriveIndexRoute = ProtectedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriveEarningsRoute = ProtectedDriveEarningsRouteImport.update({
  id: '/drive/earnings',
  path: '/drive/earnings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesIndexRoute = ProtectedMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesConversationIdRoute =
  ProtectedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMessagesNewRoute = ProtectedMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRideIndexRoute = ProtectedRideIndexRouteImport.update({
  id: '/ride/',
  path: '/ride/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRidePaymentRoute = ProtectedRidePaymentRouteImport.update({
  id: '/ride/payment',
  path: '/ride/payment',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSupportIndexRoute = ProtectedSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDrivePayoutsRefreshRoute =
  ProtectedDrivePayoutsRefreshRouteImport.update({
    id: '/drive/payouts/refresh',
    path: '/drive/payouts/refresh',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDrivePayoutsReturnRoute =
  ProtectedDrivePayoutsReturnRouteImport.update({
    id: '/drive/payouts/return',
    path: '/drive/payouts/return',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/account': typeof ProtectedAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/messages/$conversationId': typeof ProtectedMessagesConversationIdRoute
  '/messages/new': typeof ProtectedMessagesNewRoute
  '/ride/payment': typeof ProtectedRidePaymentRoute
  '/console/': typeof ProtectedConsoleIndexRoute
  '/drive/': typeof ProtectedDriveIndexRoute
  '/messages/': typeof ProtectedMessagesIndexRoute
  '/ride/': typeof ProtectedRideIndexRoute
  '/support/': typeof ProtectedSupportIndexRoute
  '/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/account': typeof ProtectedAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof ProtectedIndexRoute
  '/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/messages/$conversationId': typeof ProtectedMessagesConversationIdRoute
  '/messages/new': typeof ProtectedMessagesNewRoute
  '/ride/payment': typeof ProtectedRidePaymentRoute
  '/console': typeof ProtectedConsoleIndexRoute
  '/drive': typeof ProtectedDriveIndexRoute
  '/messages': typeof ProtectedMessagesIndexRoute
  '/ride': typeof ProtectedRideIndexRoute
  '/support': typeof ProtectedSupportIndexRoute
  '/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/drive/earnings': typeof ProtectedDriveEarningsRoute
  '/_protected/messages/$conversationId': typeof ProtectedMessagesConversationIdRoute
  '/_protected/messages/new': typeof ProtectedMessagesNewRoute
  '/_protected/ride/payment': typeof ProtectedRidePaymentRoute
  '/_protected/console/': typeof ProtectedConsoleIndexRoute
  '/_protected/drive/': typeof ProtectedDriveIndexRoute
  '/_protected/messages/': typeof ProtectedMessagesIndexRoute
  '/_protected/ride/': typeof ProtectedRideIndexRoute
  '/_protected/support/': typeof ProtectedSupportIndexRoute
  '/_protected/drive/payouts/refresh': typeof ProtectedDrivePayoutsRefreshRoute
  '/_protected/drive/payouts/return': typeof ProtectedDrivePayoutsReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/account'
    | '/auth/sign-in'
    | '/drive/earnings'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/ride/payment'
    | '/console/'
    | '/drive/'
    | '/messages/'
    | '/ride/'
    | '/support/'
    | '/drive/payouts/refresh'
    | '/drive/payouts/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/account'
    | '/auth/sign-in'
    | '/'
    | '/drive/earnings'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/ride/payment'
    | '/console'
    | '/drive'
    | '/messages'
    | '/ride'
    | '/support'
    | '/drive/payouts/refresh'
    | '/drive/payouts/return'
  id:
    | '__root__'
    | '/auth'
    | '/_protected'
    | '/_protected/account'
    | '/auth/sign-in'
    | '/_protected/'
    | '/_protected/drive/earnings'
    | '/_protected/messages/$conversationId'
    | '/_protected/messages/new'
    | '/_protected/ride/payment'
    | '/_protected/console/'
    | '/_protected/drive/'
    | '/_protected/messages/'
    | '/_protected/ride/'
    | '/_protected/support/'
    | '/_protected/drive/payouts/refresh'
    | '/_protected/drive/payouts/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/console/': {
      id: '/_protected/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ProtectedConsoleIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/': {
      id: '/_protected/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof ProtectedDriveIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/earnings': {
      id: '/_protected/drive/earnings'
      path: '/drive/earnings'
      fullPath: '/drive/earnings'
      preLoaderRoute: typeof ProtectedDriveEarningsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages/': {
      id: '/_protected/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof ProtectedMessagesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages/$conversationId': {
      id: '/_protected/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof ProtectedMessagesConversationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages/new': {
      id: '/_protected/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof ProtectedMessagesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ride/': {
      id: '/_protected/ride/'
      path: '/ride'
      fullPath: '/ride/'
      preLoaderRoute: typeof ProtectedRideIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ride/payment': {
      id: '/_protected/ride/payment'
      path: '/ride/payment'
      fullPath: '/ride/payment'
      preLoaderRoute: typeof ProtectedRidePaymentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/support/': {
      id: '/_protected/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof ProtectedSupportIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/payouts/refresh': {
      id: '/_protected/drive/payouts/refresh'
      path: '/drive/payouts/refresh'
      fullPath: '/drive/payouts/refresh'
      preLoaderRoute: typeof ProtectedDrivePayoutsRefreshRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive/payouts/return': {
      id: '/_protected/drive/payouts/return'
      path: '/drive/payouts/return'
      fullPath: '/drive/payouts/return'
      preLoaderRoute: typeof ProtectedDrivePayoutsReturnRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDriveEarningsRoute: typeof ProtectedDriveEarningsRoute
  ProtectedMessagesConversationIdRoute: typeof ProtectedMessagesConversationIdRoute
  ProtectedMessagesNewRoute: typeof ProtectedMessagesNewRoute
  ProtectedRidePaymentRoute: typeof ProtectedRidePaymentRoute
  ProtectedConsoleIndexRoute: typeof ProtectedConsoleIndexRoute
  ProtectedDriveIndexRoute: typeof ProtectedDriveIndexRoute
  ProtectedMessagesIndexRoute: typeof ProtectedMessagesIndexRoute
  ProtectedRideIndexRoute: typeof ProtectedRideIndexRoute
  ProtectedSupportIndexRoute: typeof ProtectedSupportIndexRoute
  ProtectedDrivePayoutsRefreshRoute: typeof ProtectedDrivePayoutsRefreshRoute
  ProtectedDrivePayoutsReturnRoute: typeof ProtectedDrivePayoutsReturnRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDriveEarningsRoute: ProtectedDriveEarningsRoute,
  ProtectedMessagesConversationIdRoute: ProtectedMessagesConversationIdRoute,
  ProtectedMessagesNewRoute: ProtectedMessagesNewRoute,
  ProtectedRidePaymentRoute: ProtectedRidePaymentRoute,
  ProtectedConsoleIndexRoute: ProtectedConsoleIndexRoute,
  ProtectedDriveIndexRoute: ProtectedDriveIndexRoute,
  ProtectedMessagesIndexRoute: ProtectedMessagesIndexRoute,
  ProtectedRideIndexRoute: ProtectedRideIndexRoute,
  ProtectedSupportIndexRoute: ProtectedSupportIndexRoute,
  ProtectedDrivePayoutsRefreshRoute: ProtectedDrivePayoutsRefreshRoute,
  ProtectedDrivePayoutsReturnRoute: ProtectedDrivePayoutsReturnRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
