-- Chat, owned by the chat service: a rider and driver about their trip, and a
-- rider or driver with support.
--
-- Every table is prefixed chat_ because the services share one database, and
-- a table called message is a name the next service would want too.

-- A conversation. Kind 'trip' is the rider and the driver of one trip; kind
-- 'support' is a rider or driver and whoever from support claims it.
create table if not exists chat_conversation (
  id               text primary key,
  kind             text not null,
  -- The trip a trip conversation belongs to, or the one a support conversation
  -- is about. Empty when a support conversation is about no trip.
  trip_id          text not null default '',
  -- 'open' or 'resolved'. A trip conversation is never resolved; it stops
  -- taking messages at closes_at instead.
  status           text not null default 'open',
  subject          text not null default '',
  -- The rider of a trip conversation; whoever opened a support one.
  requester_id     text not null default '',
  -- Support's claim on a support conversation. Empty until somebody takes it.
  assignee_id      text not null default '',
  -- The key a support conversation was opened with, so a retried tap opens one
  -- conversation rather than two.
  idempotency_key  text not null default '',
  -- The seq of the newest message. Bumped by the same statement that checks
  -- the conversation is open, which is what serializes the sends in it.
  last_seq         bigint not null default 0,
  -- When sending stops: the trip's end plus a grace window. Null while the
  -- trip runs. Reading never stops.
  closes_at        timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- One conversation per trip. This is what lets the lifecycle consumer and a
-- rider opening the chat both create it, and agree on which one exists.
create unique index if not exists chat_conversation_trip
  on chat_conversation (trip_id)
  where kind = 'trip';

create unique index if not exists chat_conversation_idempotency
  on chat_conversation (requester_id, idempotency_key)
  where kind = 'support' and idempotency_key <> '';

-- Support's queue: support conversations by status, oldest waiting first.
create index if not exists chat_conversation_queue
  on chat_conversation (kind, status, created_at);

-- Who is in a conversation, and how far each of them has read.
create table if not exists chat_participant (
  conversation_id  text not null references chat_conversation (id) on delete cascade,
  user_id          text not null,
  -- 'rider', 'driver' or 'support': the side of the conversation, which is
  -- what a client labels a message with.
  role             text not null,
  -- The newest seq this person has seen. Only ever moves forward.
  last_read_seq    bigint not null default 0,
  joined_at        timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

-- A person's conversations.
create index if not exists chat_participant_user
  on chat_participant (user_id, conversation_id);

-- A message, numbered within its conversation. Seq has no gaps, so a client
-- holding messages up to n asks for everything after n and misses nothing.
create table if not exists chat_message (
  conversation_id    text not null references chat_conversation (id) on delete cascade,
  seq                bigint not null,
  id                 text not null unique,
  sender_id          text not null,
  sender_role        text not null,
  -- The catalogue code of a quick reply, so a client can show it in its own
  -- language. Empty for text.
  quick_reply        text not null default '',
  body               text not null,
  -- Generated by the sending client, so a send retried after a lost response
  -- is one message.
  client_message_id  text not null default '',
  created_at         timestamptz not null default now(),
  primary key (conversation_id, seq)
);

create unique index if not exists chat_message_client_id
  on chat_message (conversation_id, sender_id, client_message_id)
  where client_message_id <> '';

-- The rate limit's question: how many has this person sent in the last minute.
create index if not exists chat_message_sender_recent
  on chat_message (sender_id, created_at);

-- A notification owed to a recipient, written with the message it is about.
--
-- Sent at not_before, and only if the recipient has not read the message by
-- then: someone looking at the conversation needs no notification about it,
-- and nobody has to know who is looking.
create table if not exists chat_push_job (
  id               bigint generated always as identity primary key,
  recipient_id     text not null,
  conversation_id  text not null references chat_conversation (id) on delete cascade,
  seq              bigint not null,
  not_before       timestamptz not null,
  -- Failed sends so far, which is what the backoff grows from.
  attempts         integer not null default 0,
  created_at       timestamptz not null default now()
);

create index if not exists chat_push_job_due on chat_push_job (not_before);

-- A device that can be notified. The token is the key because it identifies a
-- device: one signed in as someone new belongs to them now.
create table if not exists chat_push_token (
  token       text primary key,
  user_id     text not null,
  platform    text not null,
  updated_at  timestamptz not null default now()
);

create index if not exists chat_push_token_user on chat_push_token (user_id);
