// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_GetTripConversation_FullMethodName        = "/surge.chat.v1.ChatService/GetTripConversation"
	ChatService_ListConversations_FullMethodName          = "/surge.chat.v1.ChatService/ListConversations"
	ChatService_GetConversation_FullMethodName            = "/surge.chat.v1.ChatService/GetConversation"
	ChatService_ListMessages_FullMethodName               = "/surge.chat.v1.ChatService/ListMessages"
	ChatService_SendMessage_FullMethodName                = "/surge.chat.v1.ChatService/SendMessage"
	ChatService_MarkRead_FullMethodName                   = "/surge.chat.v1.ChatService/MarkRead"
	ChatService_Typing_FullMethodName                     = "/surge.chat.v1.ChatService/Typing"
	ChatService_CreateSupportConversation_FullMethodName  = "/surge.chat.v1.ChatService/CreateSupportConversation"
	ChatService_ClaimSupportConversation_FullMethodName   = "/surge.chat.v1.ChatService/ClaimSupportConversation"
	ChatService_ResolveSupportConversation_FullMethodName = "/surge.chat.v1.ChatService/ResolveSupportConversation"
	ChatService_RegisterPushToken_FullMethodName          = "/surge.chat.v1.ChatService/RegisterPushToken"
	ChatService_UnregisterPushToken_FullMethodName        = "/surge.chat.v1.ChatService/UnregisterPushToken"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatService is the conversations riders and drivers have: with each other
// about a trip, and with support.
//
// Sending is here and delivery is not. A stored message is announced on the
// WebSocket as a doorbell, ChatChanged, carrying only the conversation and its
// newest seq; the client then reads what it has not seen with ListMessages.
// This API is the source of truth, and the socket only says when to look —
// which is also why a push that arrives late, twice or never loses nothing.
//
// The caller is never a field, as in trip.proto: it arrives as metadata from
// the gateway's verified token.
type ChatServiceClient interface {
	// GetTripConversation is the rider's and driver's conversation about a trip.
	// It exists once a driver has accepted, and answers FailedPrecondition before
	// then.
	GetTripConversation(ctx context.Context, in *GetTripConversationRequest, opts ...grpc.CallOption) (*GetTripConversationResponse, error)
	// ListConversations is the caller's conversations, newest first. For
	// support, kind SUPPORT is the queue: every support conversation, whoever
	// holds it.
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	// ListMessages is a page of a conversation, oldest first within the page.
	//
	// after_seq reads forward from a seq the client already holds — what it does
	// on every ChatChanged. before_seq reads back through history. With neither,
	// it is the newest page.
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	// SendMessage stores a message: text, or one of the conversation's quick
	// replies, never both.
	//
	// Takes an idempotency key, client_message_id or an Idempotency-Key header,
	// because the caller is a phone: a send retried after a lost response is one
	// message, returned again.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// MarkRead moves the caller's read marker forward to seq, and tells the
	// others. A marker never moves back, so a late request is harmless.
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	// Typing tells the others the caller is typing. Stored nowhere, and sent on
	// at most every few seconds however often it is called.
	Typing(ctx context.Context, in *TypingRequest, opts ...grpc.CallOption) (*TypingResponse, error)
	// CreateSupportConversation opens a conversation with support, riders and
	// drivers only, with its first message.
	CreateSupportConversation(ctx context.Context, in *CreateSupportConversationRequest, opts ...grpc.CallOption) (*CreateSupportConversationResponse, error)
	// ClaimSupportConversation makes the caller, support only, the one handling
	// a conversation. Replying to an unclaimed conversation claims it too.
	ClaimSupportConversation(ctx context.Context, in *ClaimSupportConversationRequest, opts ...grpc.CallOption) (*ClaimSupportConversationResponse, error)
	// ResolveSupportConversation closes a support conversation, by support or by
	// whoever opened it. It stays readable; anything more is a new one.
	ResolveSupportConversation(ctx context.Context, in *ResolveSupportConversationRequest, opts ...grpc.CallOption) (*ResolveSupportConversationResponse, error)
	// RegisterPushToken lets this device be notified of messages the caller has
	// not read. A token signed in as someone else moves to the caller.
	RegisterPushToken(ctx context.Context, in *RegisterPushTokenRequest, opts ...grpc.CallOption) (*RegisterPushTokenResponse, error)
	// UnregisterPushToken stops notifying this device, on sign-out. A POST
	// rather than a DELETE because the gateway's CORS allows GET and POST only.
	UnregisterPushToken(ctx context.Context, in *UnregisterPushTokenRequest, opts ...grpc.CallOption) (*UnregisterPushTokenResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) GetTripConversation(ctx context.Context, in *GetTripConversationRequest, opts ...grpc.CallOption) (*GetTripConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_GetTripConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, ChatService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Typing(ctx context.Context, in *TypingRequest, opts ...grpc.CallOption) (*TypingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypingResponse)
	err := c.cc.Invoke(ctx, ChatService_Typing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateSupportConversation(ctx context.Context, in *CreateSupportConversationRequest, opts ...grpc.CallOption) (*CreateSupportConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupportConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_CreateSupportConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ClaimSupportConversation(ctx context.Context, in *ClaimSupportConversationRequest, opts ...grpc.CallOption) (*ClaimSupportConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimSupportConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_ClaimSupportConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ResolveSupportConversation(ctx context.Context, in *ResolveSupportConversationRequest, opts ...grpc.CallOption) (*ResolveSupportConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSupportConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_ResolveSupportConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RegisterPushToken(ctx context.Context, in *RegisterPushTokenRequest, opts ...grpc.CallOption) (*RegisterPushTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPushTokenResponse)
	err := c.cc.Invoke(ctx, ChatService_RegisterPushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UnregisterPushToken(ctx context.Context, in *UnregisterPushTokenRequest, opts ...grpc.CallOption) (*UnregisterPushTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterPushTokenResponse)
	err := c.cc.Invoke(ctx, ChatService_UnregisterPushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ChatService is the conversations riders and drivers have: with each other
// about a trip, and with support.
//
// Sending is here and delivery is not. A stored message is announced on the
// WebSocket as a doorbell, ChatChanged, carrying only the conversation and its
// newest seq; the client then reads what it has not seen with ListMessages.
// This API is the source of truth, and the socket only says when to look —
// which is also why a push that arrives late, twice or never loses nothing.
//
// The caller is never a field, as in trip.proto: it arrives as metadata from
// the gateway's verified token.
type ChatServiceServer interface {
	// GetTripConversation is the rider's and driver's conversation about a trip.
	// It exists once a driver has accepted, and answers FailedPrecondition before
	// then.
	GetTripConversation(context.Context, *GetTripConversationRequest) (*GetTripConversationResponse, error)
	// ListConversations is the caller's conversations, newest first. For
	// support, kind SUPPORT is the queue: every support conversation, whoever
	// holds it.
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	// ListMessages is a page of a conversation, oldest first within the page.
	//
	// after_seq reads forward from a seq the client already holds — what it does
	// on every ChatChanged. before_seq reads back through history. With neither,
	// it is the newest page.
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// SendMessage stores a message: text, or one of the conversation's quick
	// replies, never both.
	//
	// Takes an idempotency key, client_message_id or an Idempotency-Key header,
	// because the caller is a phone: a send retried after a lost response is one
	// message, returned again.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// MarkRead moves the caller's read marker forward to seq, and tells the
	// others. A marker never moves back, so a late request is harmless.
	MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	// Typing tells the others the caller is typing. Stored nowhere, and sent on
	// at most every few seconds however often it is called.
	Typing(context.Context, *TypingRequest) (*TypingResponse, error)
	// CreateSupportConversation opens a conversation with support, riders and
	// drivers only, with its first message.
	CreateSupportConversation(context.Context, *CreateSupportConversationRequest) (*CreateSupportConversationResponse, error)
	// ClaimSupportConversation makes the caller, support only, the one handling
	// a conversation. Replying to an unclaimed conversation claims it too.
	ClaimSupportConversation(context.Context, *ClaimSupportConversationRequest) (*ClaimSupportConversationResponse, error)
	// ResolveSupportConversation closes a support conversation, by support or by
	// whoever opened it. It stays readable; anything more is a new one.
	ResolveSupportConversation(context.Context, *ResolveSupportConversationRequest) (*ResolveSupportConversationResponse, error)
	// RegisterPushToken lets this device be notified of messages the caller has
	// not read. A token signed in as someone else moves to the caller.
	RegisterPushToken(context.Context, *RegisterPushTokenRequest) (*RegisterPushTokenResponse, error)
	// UnregisterPushToken stops notifying this device, on sign-out. A POST
	// rather than a DELETE because the gateway's CORS allows GET and POST only.
	UnregisterPushToken(context.Context, *UnregisterPushTokenRequest) (*UnregisterPushTokenResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) GetTripConversation(context.Context, *GetTripConversationRequest) (*GetTripConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripConversation not implemented")
}
func (UnimplementedChatServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedChatServiceServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedChatServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedChatServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedChatServiceServer) Typing(context.Context, *TypingRequest) (*TypingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Typing not implemented")
}
func (UnimplementedChatServiceServer) CreateSupportConversation(context.Context, *CreateSupportConversationRequest) (*CreateSupportConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupportConversation not implemented")
}
func (UnimplementedChatServiceServer) ClaimSupportConversation(context.Context, *ClaimSupportConversationRequest) (*ClaimSupportConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimSupportConversation not implemented")
}
func (UnimplementedChatServiceServer) ResolveSupportConversation(context.Context, *ResolveSupportConversationRequest) (*ResolveSupportConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSupportConversation not implemented")
}
func (UnimplementedChatServiceServer) RegisterPushToken(context.Context, *RegisterPushTokenRequest) (*RegisterPushTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPushToken not implemented")
}
func (UnimplementedChatServiceServer) UnregisterPushToken(context.Context, *UnregisterPushTokenRequest) (*UnregisterPushTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterPushToken not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_GetTripConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetTripConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetTripConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetTripConversation(ctx, req.(*GetTripConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Typing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Typing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Typing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Typing(ctx, req.(*TypingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateSupportConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateSupportConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateSupportConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateSupportConversation(ctx, req.(*CreateSupportConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ClaimSupportConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimSupportConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ClaimSupportConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ClaimSupportConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ClaimSupportConversation(ctx, req.(*ClaimSupportConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ResolveSupportConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSupportConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ResolveSupportConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ResolveSupportConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ResolveSupportConversation(ctx, req.(*ResolveSupportConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RegisterPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RegisterPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_RegisterPushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RegisterPushToken(ctx, req.(*RegisterPushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UnregisterPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterPushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UnregisterPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UnregisterPushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UnregisterPushToken(ctx, req.(*UnregisterPushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surge.chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTripConversation",
			Handler:    _ChatService_GetTripConversation_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _ChatService_ListConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _ChatService_GetConversation_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _ChatService_ListMessages_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _ChatService_MarkRead_Handler,
		},
		{
			MethodName: "Typing",
			Handler:    _ChatService_Typing_Handler,
		},
		{
			MethodName: "CreateSupportConversation",
			Handler:    _ChatService_CreateSupportConversation_Handler,
		},
		{
			MethodName: "ClaimSupportConversation",
			Handler:    _ChatService_ClaimSupportConversation_Handler,
		},
		{
			MethodName: "ResolveSupportConversation",
			Handler:    _ChatService_ResolveSupportConversation_Handler,
		},
		{
			MethodName: "RegisterPushToken",
			Handler:    _ChatService_RegisterPushToken_Handler,
		},
		{
			MethodName: "UnregisterPushToken",
			Handler:    _ChatService_UnregisterPushToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
