package wire_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ishakdeveloper/surge/shared/wire"
)

// geo.events is Go on both ends, so nothing like the WebSocket fixtures holds
// two languages to it. What breaks it is time: services roll one at a time, so
// during every rollout an old matcher reads records a new ingest wrote, and a
// record written before a deploy is still in the topic after it.
//
// testdata/geo is what the current code writes, regenerated by `make
// wire-fixtures` and held to the structs by CI's drift check. CI's compat job
// then points GEO_FIXTURES at the copy on `main` and runs this with the
// branch's code: a change the previous version's records would not survive
// fails before it merges. Variants and fields are only ever added.
func TestGeoEventsDecodeFromFixtures(t *testing.T) {
	dir, fromBase := os.LookupEnv("GEO_FIXTURES")
	if !fromBase {
		dir = filepath.Join("testdata", "geo")
	}

	entries, err := os.ReadDir(dir)
	if fromBase && os.IsNotExist(err) {
		t.Skipf("no geo.events fixtures at %s: the base predates them", dir)
	}
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}

	decoded := map[string]bool{}
	for _, entry := range entries {
		raw, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		event, err := wire.DecodeGeoEvent(raw)
		if err != nil {
			t.Errorf("%s no longer decodes: %v", entry.Name(), err)
			continue
		}
		decoded[event.Tag] = true
	}

	// Only for our own fixtures: an older base legitimately lacks a variant
	// added since.
	if fromBase {
		return
	}
	for _, tag := range []string{
		wire.TagDriverMoved, wire.TagDriverEnteredCell, wire.TagDriverLeftCell,
		wire.TagMatchRequested, wire.TagReserveDriver, wire.TagReserveResult,
		wire.TagOfferReplied,
	} {
		if !decoded[tag] {
			t.Errorf("no fixture for %s: add one to tools/wire-fixtures and run `make wire-fixtures`", tag)
		}
	}
}
