// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: payments.proto

package payments

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentStatus is the payment state machine, as a client sees it.
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED     PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_AUTHORIZING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_REQUIRES_ACTION PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_AUTHORIZED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_CAPTURED        PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_RELEASED        PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_FAILED          PaymentStatus = 6
	PaymentStatus_PAYMENT_STATUS_REFUNDED        PaymentStatus = 7
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_AUTHORIZING",
		2: "PAYMENT_STATUS_REQUIRES_ACTION",
		3: "PAYMENT_STATUS_AUTHORIZED",
		4: "PAYMENT_STATUS_CAPTURED",
		5: "PAYMENT_STATUS_RELEASED",
		6: "PAYMENT_STATUS_FAILED",
		7: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED":     0,
		"PAYMENT_STATUS_AUTHORIZING":     1,
		"PAYMENT_STATUS_REQUIRES_ACTION": 2,
		"PAYMENT_STATUS_AUTHORIZED":      3,
		"PAYMENT_STATUS_CAPTURED":        4,
		"PAYMENT_STATUS_RELEASED":        5,
		"PAYMENT_STATUS_FAILED":          6,
		"PAYMENT_STATUS_REFUNDED":        7,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payments_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{0}
}

type PayoutAccountStatus int32

const (
	PayoutAccountStatus_PAYOUT_ACCOUNT_STATUS_UNSPECIFIED PayoutAccountStatus = 0
	// No account yet. Earnings are recorded and owed.
	PayoutAccountStatus_PAYOUT_ACCOUNT_STATUS_NOT_STARTED PayoutAccountStatus = 1
	// An account that cannot receive money yet.
	PayoutAccountStatus_PAYOUT_ACCOUNT_STATUS_PENDING PayoutAccountStatus = 2
	// Paid as trips complete.
	PayoutAccountStatus_PAYOUT_ACCOUNT_STATUS_ACTIVE PayoutAccountStatus = 3
)

// Enum value maps for PayoutAccountStatus.
var (
	PayoutAccountStatus_name = map[int32]string{
		0: "PAYOUT_ACCOUNT_STATUS_UNSPECIFIED",
		1: "PAYOUT_ACCOUNT_STATUS_NOT_STARTED",
		2: "PAYOUT_ACCOUNT_STATUS_PENDING",
		3: "PAYOUT_ACCOUNT_STATUS_ACTIVE",
	}
	PayoutAccountStatus_value = map[string]int32{
		"PAYOUT_ACCOUNT_STATUS_UNSPECIFIED": 0,
		"PAYOUT_ACCOUNT_STATUS_NOT_STARTED": 1,
		"PAYOUT_ACCOUNT_STATUS_PENDING":     2,
		"PAYOUT_ACCOUNT_STATUS_ACTIVE":      3,
	}
)

func (x PayoutAccountStatus) Enum() *PayoutAccountStatus {
	p := new(PayoutAccountStatus)
	*p = x
	return p
}

func (x PayoutAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayoutAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_proto_enumTypes[1].Descriptor()
}

func (PayoutAccountStatus) Type() protoreflect.EnumType {
	return &file_payments_proto_enumTypes[1]
}

func (x PayoutAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayoutAccountStatus.Descriptor instead.
func (PayoutAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{1}
}

type EarningStatus int32

const (
	EarningStatus_EARNING_STATUS_UNSPECIFIED EarningStatus = 0
	// Owed, waiting for an account that can receive it.
	EarningStatus_EARNING_STATUS_UNPAID      EarningStatus = 1
	EarningStatus_EARNING_STATUS_TRANSFERRED EarningStatus = 2
	// Taken back after a refund or a dispute.
	EarningStatus_EARNING_STATUS_REVERSED EarningStatus = 3
)

// Enum value maps for EarningStatus.
var (
	EarningStatus_name = map[int32]string{
		0: "EARNING_STATUS_UNSPECIFIED",
		1: "EARNING_STATUS_UNPAID",
		2: "EARNING_STATUS_TRANSFERRED",
		3: "EARNING_STATUS_REVERSED",
	}
	EarningStatus_value = map[string]int32{
		"EARNING_STATUS_UNSPECIFIED": 0,
		"EARNING_STATUS_UNPAID":      1,
		"EARNING_STATUS_TRANSFERRED": 2,
		"EARNING_STATUS_REVERSED":    3,
	}
)

func (x EarningStatus) Enum() *EarningStatus {
	p := new(EarningStatus)
	*p = x
	return p
}

func (x EarningStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_proto_enumTypes[2].Descriptor()
}

func (EarningStatus) Type() protoreflect.EnumType {
	return &file_payments_proto_enumTypes[2]
}

func (x EarningStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EarningStatus.Descriptor instead.
func (EarningStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{2}
}

type CreateSetupIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetupIntentRequest) Reset() {
	*x = CreateSetupIntentRequest{}
	mi := &file_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupIntentRequest) ProtoMessage() {}

func (x *CreateSetupIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateSetupIntentRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{0}
}

type CreateSetupIntentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirms this setup and nothing else, and is handed straight to Stripe.js.
	ClientSecret  string `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetupIntentResponse) Reset() {
	*x = CreateSetupIntentResponse{}
	mi := &file_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupIntentResponse) ProtoMessage() {}

func (x *CreateSetupIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateSetupIntentResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSetupIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type GetPaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodRequest) Reset() {
	*x = GetPaymentMethodRequest{}
	mi := &file_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodRequest) ProtoMessage() {}

func (x *GetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{2}
}

type GetPaymentMethodResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False until the rider has saved a card. The card is then empty rather than
	// absent, like every unset field this API sends.
	Saved         bool  `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	Card          *Card `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodResponse) Reset() {
	*x = GetPaymentMethodResponse{}
	mi := &file_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodResponse) ProtoMessage() {}

func (x *GetPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentMethodResponse) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

func (x *GetPaymentMethodResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Last4         string                 `protobuf:"bytes,2,opt,name=last4,proto3" json:"last4,omitempty"`
	ExpMonth      int32                  `protobuf:"varint,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Card) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *Card) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

type GetTripPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripPaymentRequest) Reset() {
	*x = GetTripPaymentRequest{}
	mi := &file_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripPaymentRequest) ProtoMessage() {}

func (x *GetTripPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetTripPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{5}
}

func (x *GetTripPaymentRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetTripPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripPaymentResponse) Reset() {
	*x = GetTripPaymentResponse{}
	mi := &file_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripPaymentResponse) ProtoMessage() {}

func (x *GetTripPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetTripPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{6}
}

func (x *GetTripPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=surge.payments.v1.PaymentStatus" json:"status,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	CapturedCents int64                  `protobuf:"varint,5,opt,name=captured_cents,json=capturedCents,proto3" json:"captured_cents,omitempty"`
	RefundedCents int64                  `protobuf:"varint,6,opt,name=refunded_cents,json=refundedCents,proto3" json:"refunded_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	// Why a failed payment failed: no_payment_method, declined,
	// authentication_failed or expired. Empty otherwise.
	FailureReason string `protobuf:"bytes,8,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// Set while the status is REQUIRES_ACTION, for Stripe.js to run the rider's
	// authentication step, and only for the rider. Empty otherwise.
	ClientSecret  string                 `protobuf:"bytes,9,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{7}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Payment) GetCapturedCents() int64 {
	if x != nil {
		return x.CapturedCents
	}
	return 0
}

func (x *Payment) GetRefundedCents() int64 {
	if x != nil {
		return x.RefundedCents
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Payment) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPayoutAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutAccountRequest) Reset() {
	*x = GetPayoutAccountRequest{}
	mi := &file_payments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutAccountRequest) ProtoMessage() {}

func (x *GetPayoutAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutAccountRequest.ProtoReflect.Descriptor instead.
func (*GetPayoutAccountRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{8}
}

type GetPayoutAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *PayoutAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutAccountResponse) Reset() {
	*x = GetPayoutAccountResponse{}
	mi := &file_payments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutAccountResponse) ProtoMessage() {}

func (x *GetPayoutAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutAccountResponse.ProtoReflect.Descriptor instead.
func (*GetPayoutAccountResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{9}
}

func (x *GetPayoutAccountResponse) GetAccount() *PayoutAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type PayoutAccount struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status PayoutAccountStatus    `protobuf:"varint,1,opt,name=status,proto3,enum=surge.payments.v1.PayoutAccountStatus" json:"status,omitempty"`
	// The processor is waiting on the driver for something: send them back
	// through onboarding.
	RequirementsDue bool `protobuf:"varint,2,opt,name=requirements_due,json=requirementsDue,proto3" json:"requirements_due,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayoutAccount) Reset() {
	*x = PayoutAccount{}
	mi := &file_payments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutAccount) ProtoMessage() {}

func (x *PayoutAccount) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutAccount.ProtoReflect.Descriptor instead.
func (*PayoutAccount) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{10}
}

func (x *PayoutAccount) GetStatus() PayoutAccountStatus {
	if x != nil {
		return x.Status
	}
	return PayoutAccountStatus_PAYOUT_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *PayoutAccount) GetRequirementsDue() bool {
	if x != nil {
		return x.RequirementsDue
	}
	return false
}

type StartOnboardingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOnboardingRequest) Reset() {
	*x = StartOnboardingRequest{}
	mi := &file_payments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOnboardingRequest) ProtoMessage() {}

func (x *StartOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOnboardingRequest.ProtoReflect.Descriptor instead.
func (*StartOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{11}
}

type StartOnboardingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single use and short-lived: redirect to it at once, and never send it
	// anywhere else — it opens the driver's identity details to whoever follows
	// it.
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOnboardingResponse) Reset() {
	*x = StartOnboardingResponse{}
	mi := &file_payments_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOnboardingResponse) ProtoMessage() {}

func (x *StartOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOnboardingResponse.ProtoReflect.Descriptor instead.
func (*StartOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{12}
}

func (x *StartOnboardingResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListEarningsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clamped by the server.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor from a previous response.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEarningsRequest) Reset() {
	*x = ListEarningsRequest{}
	mi := &file_payments_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEarningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEarningsRequest) ProtoMessage() {}

func (x *ListEarningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEarningsRequest.ProtoReflect.Descriptor instead.
func (*ListEarningsRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{13}
}

func (x *ListEarningsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEarningsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEarningsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Earnings []*Earning             `protobuf:"bytes,1,rep,name=earnings,proto3" json:"earnings,omitempty"`
	// Empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Earned and not yet sent to the driver's account, across all pages.
	OwedCents int64 `protobuf:"varint,3,opt,name=owed_cents,json=owedCents,proto3" json:"owed_cents,omitempty"`
	// Sent to the driver's account, across all pages.
	PaidCents     int64  `protobuf:"varint,4,opt,name=paid_cents,json=paidCents,proto3" json:"paid_cents,omitempty"`
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEarningsResponse) Reset() {
	*x = ListEarningsResponse{}
	mi := &file_payments_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEarningsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEarningsResponse) ProtoMessage() {}

func (x *ListEarningsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEarningsResponse.ProtoReflect.Descriptor instead.
func (*ListEarningsResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{14}
}

func (x *ListEarningsResponse) GetEarnings() []*Earning {
	if x != nil {
		return x.Earnings
	}
	return nil
}

func (x *ListEarningsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEarningsResponse) GetOwedCents() int64 {
	if x != nil {
		return x.OwedCents
	}
	return 0
}

func (x *ListEarningsResponse) GetPaidCents() int64 {
	if x != nil {
		return x.PaidCents
	}
	return 0
}

func (x *ListEarningsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Earning struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TripId          string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	GrossCents      int64                  `protobuf:"varint,2,opt,name=gross_cents,json=grossCents,proto3" json:"gross_cents,omitempty"`
	CommissionCents int64                  `protobuf:"varint,3,opt,name=commission_cents,json=commissionCents,proto3" json:"commission_cents,omitempty"`
	NetCents        int64                  `protobuf:"varint,4,opt,name=net_cents,json=netCents,proto3" json:"net_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          EarningStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=surge.payments.v1.EarningStatus" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Earning) Reset() {
	*x = Earning{}
	mi := &file_payments_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Earning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Earning) ProtoMessage() {}

func (x *Earning) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Earning.ProtoReflect.Descriptor instead.
func (*Earning) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{15}
}

func (x *Earning) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Earning) GetGrossCents() int64 {
	if x != nil {
		return x.GrossCents
	}
	return 0
}

func (x *Earning) GetCommissionCents() int64 {
	if x != nil {
		return x.CommissionCents
	}
	return 0
}

func (x *Earning) GetNetCents() int64 {
	if x != nil {
		return x.NetCents
	}
	return 0
}

func (x *Earning) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Earning) GetStatus() EarningStatus {
	if x != nil {
		return x.Status
	}
	return EarningStatus_EARNING_STATUS_UNSPECIFIED
}

func (x *Earning) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_payments_proto protoreflect.FileDescriptor

const file_payments_proto_rawDesc = "" +
	"\n" +
	"\x0epayments.proto\x12\x11surge.payments.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1a\n" +
	"\x18CreateSetupIntentRequest\"@\n" +
	"\x19CreateSetupIntentResponse\x12#\n" +
	"\rclient_secret\x18\x01 \x01(\tR\fclientSecret\"\x19\n" +
	"\x17GetPaymentMethodRequest\"]\n" +
	"\x18GetPaymentMethodResponse\x12\x14\n" +
	"\x05saved\x18\x01 \x01(\bR\x05saved\x12+\n" +
	"\x04card\x18\x02 \x01(\v2\x17.surge.payments.v1.CardR\x04card\"j\n" +
	"\x04Card\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05last4\x18\x02 \x01(\tR\x05last4\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\x05R\aexpYear\"?\n" +
	"\x15GetTripPaymentRequest\x12&\n" +
	"\atrip_id\x18\x01 \x01(\tB\r\x92A\n" +
	"\xa2\x02\atrip-idR\x06tripId\"N\n" +
	"\x16GetTripPaymentResponse\x124\n" +
	"\apayment\x18\x01 \x01(\v2\x1a.surge.payments.v1.PaymentR\apayment\"\x83\x04\n" +
	"\aPayment\x12 \n" +
	"\x02id\x18\x01 \x01(\tB\x10\x92A\r\xa2\x02\n" +
	"payment-idR\x02id\x12&\n" +
	"\atrip_id\x18\x02 \x01(\tB\r\x92A\n" +
	"\xa2\x02\atrip-idR\x06tripId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .surge.payments.v1.PaymentStatusR\x06status\x12.\n" +
	"\famount_cents\x18\x04 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\vamountCents\x122\n" +
	"\x0ecaptured_cents\x18\x05 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\rcapturedCents\x122\n" +
	"\x0erefunded_cents\x18\x06 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\rrefundedCents\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12%\n" +
	"\x0efailure_reason\x18\b \x01(\tR\rfailureReason\x12#\n" +
	"\rclient_secret\x18\t \x01(\tR\fclientSecret\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x19\n" +
	"\x17GetPayoutAccountRequest\"V\n" +
	"\x18GetPayoutAccountResponse\x12:\n" +
	"\aaccount\x18\x01 \x01(\v2 .surge.payments.v1.PayoutAccountR\aaccount\"z\n" +
	"\rPayoutAccount\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.surge.payments.v1.PayoutAccountStatusR\x06status\x12)\n" +
	"\x10requirements_due\x18\x02 \x01(\bR\x0frequirementsDue\"\x18\n" +
	"\x16StartOnboardingRequest\"+\n" +
	"\x17StartOnboardingResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Q\n" +
	"\x13ListEarningsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\xea\x01\n" +
	"\x14ListEarningsResponse\x126\n" +
	"\bearnings\x18\x01 \x03(\v2\x1a.surge.payments.v1.EarningR\bearnings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12*\n" +
	"\n" +
	"owed_cents\x18\x03 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\towedCents\x12*\n" +
	"\n" +
	"paid_cents\x18\x04 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\tpaidCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xd2\x02\n" +
	"\aEarning\x12&\n" +
	"\atrip_id\x18\x01 \x01(\tB\r\x92A\n" +
	"\xa2\x02\atrip-idR\x06tripId\x12,\n" +
	"\vgross_cents\x18\x02 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\n" +
	"grossCents\x126\n" +
	"\x10commission_cents\x18\x03 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\x0fcommissionCents\x12(\n" +
	"\tnet_cents\x18\x04 \x01(\x03B\v\x92A\b\xa2\x02\x05centsR\bnetCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .surge.payments.v1.EarningStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x84\x02\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_AUTHORIZING\x10\x01\x12\"\n" +
	"\x1ePAYMENT_STATUS_REQUIRES_ACTION\x10\x02\x12\x1d\n" +
	"\x19PAYMENT_STATUS_AUTHORIZED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_CAPTURED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_RELEASED\x10\x05\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x06\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\a*\xa8\x01\n" +
	"\x13PayoutAccountStatus\x12%\n" +
	"!PAYOUT_ACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!PAYOUT_ACCOUNT_STATUS_NOT_STARTED\x10\x01\x12!\n" +
	"\x1dPAYOUT_ACCOUNT_STATUS_PENDING\x10\x02\x12 \n" +
	"\x1cPAYOUT_ACCOUNT_STATUS_ACTIVE\x10\x03*\x87\x01\n" +
	"\rEarningStatus\x12\x1e\n" +
	"\x1aEARNING_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EARNING_STATUS_UNPAID\x10\x01\x12\x1e\n" +
	"\x1aEARNING_STATUS_TRANSFERRED\x10\x02\x12\x1b\n" +
	"\x17EARNING_STATUS_REVERSED\x10\x032\x8c\r\n" +
	"\x0fPaymentsService\x12\x9f\x02\n" +
	"\x11CreateSetupIntent\x12+.surge.payments.v1.CreateSetupIntentRequest\x1a,.surge.payments.v1.CreateSetupIntentResponse\"\xae\x01\x92A\x85\x01\n" +
	"\bpayments*\x11createSetupIntentJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/payments/setup-intents\x12\x89\x02\n" +
	"\x10GetPaymentMethod\x12*.surge.payments.v1.GetPaymentMethodRequest\x1a+.surge.payments.v1.GetPaymentMethodResponse\"\x9b\x01\x92A}\n" +
	"\bpayments*\tgetMethodJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/payments/method\x12\x8d\x02\n" +
	"\x0eGetTripPayment\x12(.surge.payments.v1.GetTripPaymentRequest\x1a).surge.payments.v1.GetTripPaymentResponse\"\xa5\x01\x92A~\n" +
	"\bpayments*\n" +
	"getForTripJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/payments/trips/{trip_id}\x12\x99\x02\n" +
	"\x10GetPayoutAccount\x12*.surge.payments.v1.GetPayoutAccountRequest\x1a+.surge.payments.v1.GetPayoutAccountResponse\"\xab\x01\x92A\x84\x01\n" +
	"\bpayments*\x10getPayoutAccountJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/payments/payout-account\x12\x98\x02\n" +
	"\x0fStartOnboarding\x12).surge.payments.v1.StartOnboardingRequest\x1a*.surge.payments.v1.StartOnboardingResponse\"\xad\x01\x92A\x83\x01\n" +
	"\bpayments*\x0fstartOnboardingJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/payments/payout-account\x12\x83\x02\n" +
	"\fListEarnings\x12&.surge.payments.v1.ListEarningsRequest\x1a'.surge.payments.v1.ListEarningsResponse\"\xa1\x01\x92A\x80\x01\n" +
	"\bpayments*\flistEarningsJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/payments/earningsB@Z>github.com/ishakdeveloper/surge/shared/proto/payments;paymentsb\x06proto3"

var (
	file_payments_proto_rawDescOnce sync.Once
	file_payments_proto_rawDescData []byte
)

func file_payments_proto_rawDescGZIP() []byte {
	file_payments_proto_rawDescOnce.Do(func() {
		file_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)))
	})
	return file_payments_proto_rawDescData
}

var file_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_payments_proto_goTypes = []any{
	(PaymentStatus)(0),                // 0: surge.payments.v1.PaymentStatus
	(PayoutAccountStatus)(0),          // 1: surge.payments.v1.PayoutAccountStatus
	(EarningStatus)(0),                // 2: surge.payments.v1.EarningStatus
	(*CreateSetupIntentRequest)(nil),  // 3: surge.payments.v1.CreateSetupIntentRequest
	(*CreateSetupIntentResponse)(nil), // 4: surge.payments.v1.CreateSetupIntentResponse
	(*GetPaymentMethodRequest)(nil),   // 5: surge.payments.v1.GetPaymentMethodRequest
	(*GetPaymentMethodResponse)(nil),  // 6: surge.payments.v1.GetPaymentMethodResponse
	(*Card)(nil),                      // 7: surge.payments.v1.Card
	(*GetTripPaymentRequest)(nil),     // 8: surge.payments.v1.GetTripPaymentRequest
	(*GetTripPaymentResponse)(nil),    // 9: surge.payments.v1.GetTripPaymentResponse
	(*Payment)(nil),                   // 10: surge.payments.v1.Payment
	(*GetPayoutAccountRequest)(nil),   // 11: surge.payments.v1.GetPayoutAccountRequest
	(*GetPayoutAccountResponse)(nil),  // 12: surge.payments.v1.GetPayoutAccountResponse
	(*PayoutAccount)(nil),             // 13: surge.payments.v1.PayoutAccount
	(*StartOnboardingRequest)(nil),    // 14: surge.payments.v1.StartOnboardingRequest
	(*StartOnboardingResponse)(nil),   // 15: surge.payments.v1.StartOnboardingResponse
	(*ListEarningsRequest)(nil),       // 16: surge.payments.v1.ListEarningsRequest
	(*ListEarningsResponse)(nil),      // 17: surge.payments.v1.ListEarningsResponse
	(*Earning)(nil),                   // 18: surge.payments.v1.Earning
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_payments_proto_depIdxs = []int32{
	7,  // 0: surge.payments.v1.GetPaymentMethodResponse.card:type_name -> surge.payments.v1.Card
	10, // 1: surge.payments.v1.GetTripPaymentResponse.payment:type_name -> surge.payments.v1.Payment
	0,  // 2: surge.payments.v1.Payment.status:type_name -> surge.payments.v1.PaymentStatus
	19, // 3: surge.payments.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: surge.payments.v1.Payment.updated_at:type_name -> google.protobuf.Timestamp
	13, // 5: surge.payments.v1.GetPayoutAccountResponse.account:type_name -> surge.payments.v1.PayoutAccount
	1,  // 6: surge.payments.v1.PayoutAccount.status:type_name -> surge.payments.v1.PayoutAccountStatus
	18, // 7: surge.payments.v1.ListEarningsResponse.earnings:type_name -> surge.payments.v1.Earning
	2,  // 8: surge.payments.v1.Earning.status:type_name -> surge.payments.v1.EarningStatus
	19, // 9: surge.payments.v1.Earning.created_at:type_name -> google.protobuf.Timestamp
	3,  // 10: surge.payments.v1.PaymentsService.CreateSetupIntent:input_type -> surge.payments.v1.CreateSetupIntentRequest
	5,  // 11: surge.payments.v1.PaymentsService.GetPaymentMethod:input_type -> surge.payments.v1.GetPaymentMethodRequest
	8,  // 12: surge.payments.v1.PaymentsService.GetTripPayment:input_type -> surge.payments.v1.GetTripPaymentRequest
	11, // 13: surge.payments.v1.PaymentsService.GetPayoutAccount:input_type -> surge.payments.v1.GetPayoutAccountRequest
	14, // 14: surge.payments.v1.PaymentsService.StartOnboarding:input_type -> surge.payments.v1.StartOnboardingRequest
	16, // 15: surge.payments.v1.PaymentsService.ListEarnings:input_type -> surge.payments.v1.ListEarningsRequest
	4,  // 16: surge.payments.v1.PaymentsService.CreateSetupIntent:output_type -> surge.payments.v1.CreateSetupIntentResponse
	6,  // 17: surge.payments.v1.PaymentsService.GetPaymentMethod:output_type -> surge.payments.v1.GetPaymentMethodResponse
	9,  // 18: surge.payments.v1.PaymentsService.GetTripPayment:output_type -> surge.payments.v1.GetTripPaymentResponse
	12, // 19: surge.payments.v1.PaymentsService.GetPayoutAccount:output_type -> surge.payments.v1.GetPayoutAccountResponse
	15, // 20: surge.payments.v1.PaymentsService.StartOnboarding:output_type -> surge.payments.v1.StartOnboardingResponse
	17, // 21: surge.payments.v1.PaymentsService.ListEarnings:output_type -> surge.payments.v1.ListEarningsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_payments_proto_init() }
func file_payments_proto_init() {
	if File_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_proto_goTypes,
		DependencyIndexes: file_payments_proto_depIdxs,
		EnumInfos:         file_payments_proto_enumTypes,
		MessageInfos:      file_payments_proto_msgTypes,
	}.Build()
	File_payments_proto = out.File
	file_payments_proto_goTypes = nil
	file_payments_proto_depIdxs = nil
}
