// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: profile.proto

package profile

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// A first name, as the person gave it. Empty until they do.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A signed link to the photo, good for at least an hour and the same for
	// every caller within the hour. Empty without a photo.
	AvatarUrl     string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetMyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfileRequest) Reset() {
	*x = GetMyProfileRequest{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfileRequest) ProtoMessage() {}

func (x *GetMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfileRequest.ProtoReflect.Descriptor instead.
func (*GetMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

type GetMyProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfileResponse) Reset() {
	*x = GetMyProfileResponse{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfileResponse) ProtoMessage() {}

func (x *GetMyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfileResponse.ProtoReflect.Descriptor instead.
func (*GetMyProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateMyProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trimmed, 1 to 40 characters.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileRequest) Reset() {
	*x = UpdateMyProfileRequest{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileRequest) ProtoMessage() {}

func (x *UpdateMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMyProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type UpdateMyProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileResponse) Reset() {
	*x = UpdateMyProfileResponse{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileResponse) ProtoMessage() {}

func (x *UpdateMyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMyProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UploadAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A JPEG, PNG or WebP photo of at most 5 MB and 8000 pixels a side. Cropped
	// to its middle square and scaled to 512 pixels here.
	Image         []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UploadAvatarRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *UploadAvatarResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type RemoveAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAvatarRequest) Reset() {
	*x = RemoveAvatarRequest{}
	mi := &file_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAvatarRequest) ProtoMessage() {}

func (x *RemoveAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAvatarRequest.ProtoReflect.Descriptor instead.
func (*RemoveAvatarRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

type RemoveAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAvatarResponse) Reset() {
	*x = RemoveAvatarResponse{}
	mi := &file_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAvatarResponse) ProtoMessage() {}

func (x *RemoveAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAvatarResponse.ProtoReflect.Descriptor instead.
func (*RemoveAvatarResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveAvatarResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{10}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\x10surge.profile.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"s\n" +
	"\aProfile\x12&\n" +
	"\auser_id\x18\x01 \x01(\tB\r\x92A\n" +
	"\xa2\x02\auser-idR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\x15\n" +
	"\x13GetMyProfileRequest\"K\n" +
	"\x14GetMyProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.surge.profile.v1.ProfileR\aprofile\";\n" +
	"\x16UpdateMyProfileRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"N\n" +
	"\x17UpdateMyProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.surge.profile.v1.ProfileR\aprofile\"+\n" +
	"\x13UploadAvatarRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"K\n" +
	"\x14UploadAvatarResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.surge.profile.v1.ProfileR\aprofile\"\x15\n" +
	"\x13RemoveAvatarRequest\"K\n" +
	"\x14RemoveAvatarResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.surge.profile.v1.ProfileR\aprofile\";\n" +
	"\x11GetProfileRequest\x12&\n" +
	"\auser_id\x18\x01 \x01(\tB\r\x92A\n" +
	"\xa2\x02\auser-idR\x06userId\"I\n" +
	"\x12GetProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.surge.profile.v1.ProfileR\aprofile2\x90\n" +
	"\n" +
	"\x0eProfileService\x12\xf1\x01\n" +
	"\fGetMyProfile\x12%.surge.profile.v1.GetMyProfileRequest\x1a&.surge.profile.v1.GetMyProfileResponse\"\x91\x01\x92A{\n" +
	"\bprofiles*\agetMineJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\r\x12\v/v1/profile\x12\x80\x02\n" +
	"\x0fUpdateMyProfile\x12(.surge.profile.v1.UpdateMyProfileRequest\x1a).surge.profile.v1.UpdateMyProfileResponse\"\x97\x01\x92A~\n" +
	"\bprofiles*\n" +
	"updateMineJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/profile\x12\x81\x02\n" +
	"\fUploadAvatar\x12%.surge.profile.v1.UploadAvatarRequest\x1a&.surge.profile.v1.UploadAvatarResponse\"\xa1\x01\x92A\x80\x01\n" +
	"\bprofiles*\fuploadAvatarJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/profile/avatar\x12\x88\x02\n" +
	"\fRemoveAvatar\x12%.surge.profile.v1.RemoveAvatarRequest\x1a&.surge.profile.v1.RemoveAvatarResponse\"\xa8\x01\x92A\x80\x01\n" +
	"\bprofiles*\fremoveAvatarJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/profile/avatar/delete\x12\xf7\x01\n" +
	"\n" +
	"GetProfile\x12#.surge.profile.v1.GetProfileRequest\x1a$.surge.profile.v1.GetProfileResponse\"\x9d\x01\x92Aw\n" +
	"\bprofiles*\x03getJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/profileB>Z<github.com/ishakdeveloper/surge/shared/proto/profile;profileb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_profile_proto_goTypes = []any{
	(*Profile)(nil),                 // 0: surge.profile.v1.Profile
	(*GetMyProfileRequest)(nil),     // 1: surge.profile.v1.GetMyProfileRequest
	(*GetMyProfileResponse)(nil),    // 2: surge.profile.v1.GetMyProfileResponse
	(*UpdateMyProfileRequest)(nil),  // 3: surge.profile.v1.UpdateMyProfileRequest
	(*UpdateMyProfileResponse)(nil), // 4: surge.profile.v1.UpdateMyProfileResponse
	(*UploadAvatarRequest)(nil),     // 5: surge.profile.v1.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),    // 6: surge.profile.v1.UploadAvatarResponse
	(*RemoveAvatarRequest)(nil),     // 7: surge.profile.v1.RemoveAvatarRequest
	(*RemoveAvatarResponse)(nil),    // 8: surge.profile.v1.RemoveAvatarResponse
	(*GetProfileRequest)(nil),       // 9: surge.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),      // 10: surge.profile.v1.GetProfileResponse
}
var file_profile_proto_depIdxs = []int32{
	0,  // 0: surge.profile.v1.GetMyProfileResponse.profile:type_name -> surge.profile.v1.Profile
	0,  // 1: surge.profile.v1.UpdateMyProfileResponse.profile:type_name -> surge.profile.v1.Profile
	0,  // 2: surge.profile.v1.UploadAvatarResponse.profile:type_name -> surge.profile.v1.Profile
	0,  // 3: surge.profile.v1.RemoveAvatarResponse.profile:type_name -> surge.profile.v1.Profile
	0,  // 4: surge.profile.v1.GetProfileResponse.profile:type_name -> surge.profile.v1.Profile
	1,  // 5: surge.profile.v1.ProfileService.GetMyProfile:input_type -> surge.profile.v1.GetMyProfileRequest
	3,  // 6: surge.profile.v1.ProfileService.UpdateMyProfile:input_type -> surge.profile.v1.UpdateMyProfileRequest
	5,  // 7: surge.profile.v1.ProfileService.UploadAvatar:input_type -> surge.profile.v1.UploadAvatarRequest
	7,  // 8: surge.profile.v1.ProfileService.RemoveAvatar:input_type -> surge.profile.v1.RemoveAvatarRequest
	9,  // 9: surge.profile.v1.ProfileService.GetProfile:input_type -> surge.profile.v1.GetProfileRequest
	2,  // 10: surge.profile.v1.ProfileService.GetMyProfile:output_type -> surge.profile.v1.GetMyProfileResponse
	4,  // 11: surge.profile.v1.ProfileService.UpdateMyProfile:output_type -> surge.profile.v1.UpdateMyProfileResponse
	6,  // 12: surge.profile.v1.ProfileService.UploadAvatar:output_type -> surge.profile.v1.UploadAvatarResponse
	8,  // 13: surge.profile.v1.ProfileService.RemoveAvatar:output_type -> surge.profile.v1.RemoveAvatarResponse
	10, // 14: surge.profile.v1.ProfileService.GetProfile:output_type -> surge.profile.v1.GetProfileResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
