// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: sim.proto

package sim

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Simulator struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Drivers int32                  `protobuf:"varint,1,opt,name=drivers,proto3" json:"drivers,omitempty"`
	// Running is how many driver goroutines are actually up, which lags
	// `drivers` for a moment after a rescale.
	Running        int32 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	PingsTotal     int64 `protobuf:"varint,3,opt,name=pings_total,json=pingsTotal,proto3" json:"pings_total,omitempty"`
	PingIntervalMs int32 `protobuf:"varint,4,opt,name=ping_interval_ms,json=pingIntervalMs,proto3" json:"ping_interval_ms,omitempty"`
	// Drivers divided by the interval: ingest's load, stated.
	TargetPingsPerSecond float64 `protobuf:"fixed64,5,opt,name=target_pings_per_second,json=targetPingsPerSecond,proto3" json:"target_pings_per_second,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Simulator) Reset() {
	*x = Simulator{}
	mi := &file_sim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simulator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simulator) ProtoMessage() {}

func (x *Simulator) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simulator.ProtoReflect.Descriptor instead.
func (*Simulator) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{0}
}

func (x *Simulator) GetDrivers() int32 {
	if x != nil {
		return x.Drivers
	}
	return 0
}

func (x *Simulator) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *Simulator) GetPingsTotal() int64 {
	if x != nil {
		return x.PingsTotal
	}
	return 0
}

func (x *Simulator) GetPingIntervalMs() int32 {
	if x != nil {
		return x.PingIntervalMs
	}
	return 0
}

func (x *Simulator) GetTargetPingsPerSecond() float64 {
	if x != nil {
		return x.TargetPingsPerSecond
	}
	return 0
}

type GetSimulatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimulatorRequest) Reset() {
	*x = GetSimulatorRequest{}
	mi := &file_sim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimulatorRequest) ProtoMessage() {}

func (x *GetSimulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimulatorRequest.ProtoReflect.Descriptor instead.
func (*GetSimulatorRequest) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{1}
}

type GetSimulatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulator     *Simulator             `protobuf:"bytes,1,opt,name=simulator,proto3" json:"simulator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimulatorResponse) Reset() {
	*x = GetSimulatorResponse{}
	mi := &file_sim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimulatorResponse) ProtoMessage() {}

func (x *GetSimulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimulatorResponse.ProtoReflect.Descriptor instead.
func (*GetSimulatorResponse) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{2}
}

func (x *GetSimulatorResponse) GetSimulator() *Simulator {
	if x != nil {
		return x.Simulator
	}
	return nil
}

type ConfigureSimulatorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Drivers        int32                  `protobuf:"varint,1,opt,name=drivers,proto3" json:"drivers,omitempty"`
	PingIntervalMs int32                  `protobuf:"varint,2,opt,name=ping_interval_ms,json=pingIntervalMs,proto3" json:"ping_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureSimulatorRequest) Reset() {
	*x = ConfigureSimulatorRequest{}
	mi := &file_sim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSimulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSimulatorRequest) ProtoMessage() {}

func (x *ConfigureSimulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSimulatorRequest.ProtoReflect.Descriptor instead.
func (*ConfigureSimulatorRequest) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureSimulatorRequest) GetDrivers() int32 {
	if x != nil {
		return x.Drivers
	}
	return 0
}

func (x *ConfigureSimulatorRequest) GetPingIntervalMs() int32 {
	if x != nil {
		return x.PingIntervalMs
	}
	return 0
}

type ConfigureSimulatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulator     *Simulator             `protobuf:"bytes,1,opt,name=simulator,proto3" json:"simulator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSimulatorResponse) Reset() {
	*x = ConfigureSimulatorResponse{}
	mi := &file_sim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSimulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSimulatorResponse) ProtoMessage() {}

func (x *ConfigureSimulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSimulatorResponse.ProtoReflect.Descriptor instead.
func (*ConfigureSimulatorResponse) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureSimulatorResponse) GetSimulator() *Simulator {
	if x != nil {
		return x.Simulator
	}
	return nil
}

var File_sim_proto protoreflect.FileDescriptor

const file_sim_proto_rawDesc = "" +
	"\n" +
	"\tsim.proto\x12\fsurge.sim.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc1\x01\n" +
	"\tSimulator\x12\x18\n" +
	"\adrivers\x18\x01 \x01(\x05R\adrivers\x12\x18\n" +
	"\arunning\x18\x02 \x01(\x05R\arunning\x12\x1f\n" +
	"\vpings_total\x18\x03 \x01(\x03R\n" +
	"pingsTotal\x12(\n" +
	"\x10ping_interval_ms\x18\x04 \x01(\x05R\x0epingIntervalMs\x125\n" +
	"\x17target_pings_per_second\x18\x05 \x01(\x01R\x14targetPingsPerSecond\"\x15\n" +
	"\x13GetSimulatorRequest\"M\n" +
	"\x14GetSimulatorResponse\x125\n" +
	"\tsimulator\x18\x01 \x01(\v2\x17.surge.sim.v1.SimulatorR\tsimulator\"_\n" +
	"\x19ConfigureSimulatorRequest\x12\x18\n" +
	"\adrivers\x18\x01 \x01(\x05R\adrivers\x12(\n" +
	"\x10ping_interval_ms\x18\x02 \x01(\x05R\x0epingIntervalMs\"S\n" +
	"\x1aConfigureSimulatorResponse\x125\n" +
	"\tsimulator\x18\x01 \x01(\v2\x17.surge.sim.v1.SimulatorR\tsimulator2\x83\x04\n" +
	"\x10SimulatorService\x12\xe8\x01\n" +
	"\fGetSimulator\x12!.surge.sim.v1.GetSimulatorRequest\x1a\".surge.sim.v1.GetSimulatorResponse\"\x90\x01\x92Ax\n" +
	"\tsimulator*\x03getJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/simulator\x12\x83\x02\n" +
	"\x12ConfigureSimulator\x12'.surge.sim.v1.ConfigureSimulatorRequest\x1a(.surge.sim.v1.ConfigureSimulatorResponse\"\x99\x01\x92A~\n" +
	"\tsimulator*\tconfigureJf\n" +
	"\adefault\x12[\n" +
	"9The gateway's error shape, from its custom error handler.\x12\x1e\n" +
	"\x1c\x1a\x1a.surge.common.v1.ErrorBody\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/simulatorB6Z4github.com/ishakdeveloper/surge/shared/proto/sim;simb\x06proto3"

var (
	file_sim_proto_rawDescOnce sync.Once
	file_sim_proto_rawDescData []byte
)

func file_sim_proto_rawDescGZIP() []byte {
	file_sim_proto_rawDescOnce.Do(func() {
		file_sim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sim_proto_rawDesc), len(file_sim_proto_rawDesc)))
	})
	return file_sim_proto_rawDescData
}

var file_sim_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sim_proto_goTypes = []any{
	(*Simulator)(nil),                  // 0: surge.sim.v1.Simulator
	(*GetSimulatorRequest)(nil),        // 1: surge.sim.v1.GetSimulatorRequest
	(*GetSimulatorResponse)(nil),       // 2: surge.sim.v1.GetSimulatorResponse
	(*ConfigureSimulatorRequest)(nil),  // 3: surge.sim.v1.ConfigureSimulatorRequest
	(*ConfigureSimulatorResponse)(nil), // 4: surge.sim.v1.ConfigureSimulatorResponse
}
var file_sim_proto_depIdxs = []int32{
	0, // 0: surge.sim.v1.GetSimulatorResponse.simulator:type_name -> surge.sim.v1.Simulator
	0, // 1: surge.sim.v1.ConfigureSimulatorResponse.simulator:type_name -> surge.sim.v1.Simulator
	1, // 2: surge.sim.v1.SimulatorService.GetSimulator:input_type -> surge.sim.v1.GetSimulatorRequest
	3, // 3: surge.sim.v1.SimulatorService.ConfigureSimulator:input_type -> surge.sim.v1.ConfigureSimulatorRequest
	2, // 4: surge.sim.v1.SimulatorService.GetSimulator:output_type -> surge.sim.v1.GetSimulatorResponse
	4, // 5: surge.sim.v1.SimulatorService.ConfigureSimulator:output_type -> surge.sim.v1.ConfigureSimulatorResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sim_proto_init() }
func file_sim_proto_init() {
	if File_sim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sim_proto_rawDesc), len(file_sim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sim_proto_goTypes,
		DependencyIndexes: file_sim_proto_depIdxs,
		MessageInfos:      file_sim_proto_msgTypes,
	}.Build()
	File_sim_proto = out.File
	file_sim_proto_goTypes = nil
	file_sim_proto_depIdxs = nil
}
