// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: sim.proto

package sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulatorService_GetSimulator_FullMethodName       = "/surge.sim.v1.SimulatorService/GetSimulator"
	SimulatorService_ConfigureSimulator_FullMethodName = "/surge.sim.v1.SimulatorService/ConfigureSimulator"
)

// SimulatorServiceClient is the client API for SimulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulatorService is the load generator's control panel: how many drivers,
// reporting how often.
//
// Behind the gateway like every other API, rather than on the simulator's own
// port, for two reasons. The console should reach one origin with one token.
// And turning the knob from 500 drivers to 50,000 is an operation on shared
// infrastructure, so it is ops only — enforced by the simulator itself against
// the caller the gateway forwards, the same way the trip service enforces who
// may read a trip.
type SimulatorServiceClient interface {
	// GetSimulator is the fleet's size and rate, as configured and as running.
	GetSimulator(ctx context.Context, in *GetSimulatorRequest, opts ...grpc.CallOption) (*GetSimulatorResponse, error)
	// ConfigureSimulator rescales the fleet.
	//
	// The whole desired configuration rather than a partial patch: the console
	// shows both values and sends both, and a request that must carry every
	// field is one the generated client can type as exactly that.
	ConfigureSimulator(ctx context.Context, in *ConfigureSimulatorRequest, opts ...grpc.CallOption) (*ConfigureSimulatorResponse, error)
}

type simulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulatorServiceClient(cc grpc.ClientConnInterface) SimulatorServiceClient {
	return &simulatorServiceClient{cc}
}

func (c *simulatorServiceClient) GetSimulator(ctx context.Context, in *GetSimulatorRequest, opts ...grpc.CallOption) (*GetSimulatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimulatorResponse)
	err := c.cc.Invoke(ctx, SimulatorService_GetSimulator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) ConfigureSimulator(ctx context.Context, in *ConfigureSimulatorRequest, opts ...grpc.CallOption) (*ConfigureSimulatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureSimulatorResponse)
	err := c.cc.Invoke(ctx, SimulatorService_ConfigureSimulator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulatorServiceServer is the server API for SimulatorService service.
// All implementations must embed UnimplementedSimulatorServiceServer
// for forward compatibility.
//
// SimulatorService is the load generator's control panel: how many drivers,
// reporting how often.
//
// Behind the gateway like every other API, rather than on the simulator's own
// port, for two reasons. The console should reach one origin with one token.
// And turning the knob from 500 drivers to 50,000 is an operation on shared
// infrastructure, so it is ops only — enforced by the simulator itself against
// the caller the gateway forwards, the same way the trip service enforces who
// may read a trip.
type SimulatorServiceServer interface {
	// GetSimulator is the fleet's size and rate, as configured and as running.
	GetSimulator(context.Context, *GetSimulatorRequest) (*GetSimulatorResponse, error)
	// ConfigureSimulator rescales the fleet.
	//
	// The whole desired configuration rather than a partial patch: the console
	// shows both values and sends both, and a request that must carry every
	// field is one the generated client can type as exactly that.
	ConfigureSimulator(context.Context, *ConfigureSimulatorRequest) (*ConfigureSimulatorResponse, error)
	mustEmbedUnimplementedSimulatorServiceServer()
}

// UnimplementedSimulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulatorServiceServer struct{}

func (UnimplementedSimulatorServiceServer) GetSimulator(context.Context, *GetSimulatorRequest) (*GetSimulatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimulator not implemented")
}
func (UnimplementedSimulatorServiceServer) ConfigureSimulator(context.Context, *ConfigureSimulatorRequest) (*ConfigureSimulatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureSimulator not implemented")
}
func (UnimplementedSimulatorServiceServer) mustEmbedUnimplementedSimulatorServiceServer() {}
func (UnimplementedSimulatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeSimulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulatorServiceServer will
// result in compilation errors.
type UnsafeSimulatorServiceServer interface {
	mustEmbedUnimplementedSimulatorServiceServer()
}

func RegisterSimulatorServiceServer(s grpc.ServiceRegistrar, srv SimulatorServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulatorService_ServiceDesc, srv)
}

func _SimulatorService_GetSimulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).GetSimulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_GetSimulator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).GetSimulator(ctx, req.(*GetSimulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_ConfigureSimulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSimulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).ConfigureSimulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_ConfigureSimulator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).ConfigureSimulator(ctx, req.(*ConfigureSimulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulatorService_ServiceDesc is the grpc.ServiceDesc for SimulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surge.sim.v1.SimulatorService",
	HandlerType: (*SimulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSimulator",
			Handler:    _SimulatorService_GetSimulator_Handler,
		},
		{
			MethodName: "ConfigureSimulator",
			Handler:    _SimulatorService_ConfigureSimulator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sim.proto",
}
