/**
 * GENERATED — do not edit. Run `make proto`.
 *
 * The Go API, as this codebase consumes it. Generated by
 * `@effect/openapi-generator` from the OpenAPI document grpc-gateway emits from
 * `proto/trip.proto`, which is the single source of truth for the gRPC service,
 * the REST reverse proxy, the published spec and this file.
 *
 * `HttpApiBuilder` is never used: no TypeScript implements this. What it gives
 * the browser is a typed client and runtime decoding at the boundary, which is
 * the difference between a wrong response failing here with a readable error and
 * failing three components later as `undefined is not an object`.
 *
 * `scripts/generate-api-client.mjs` describes the two things the document cannot
 * say for itself — that the gateway's `EmitUnpopulated` makes every field
 * present, and that a `format` names a branded id or a 64-bit number.
 */
import * as Schema from "effect/Schema";
import {
  HttpApi,
  HttpApiEndpoint,
  HttpApiGroup,
  HttpApiSchema,
  OpenApi,
} from "effect/unstable/httpapi";
import {
  CentsFromString,
  DriverId,
  ErrorCode,
  FareId,
  Int64FromString,
  RiderId,
  TripId,
} from "./Primitives.js";
// non-recursive definitions
export type V1ListTripsResponse = typeof V1ListTripsResponse.Type;
export const V1ListTripsResponse = Schema.Struct({
  "trips": Schema.Array(Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  })),
  "nextPageToken": Schema.String.annotate({ "description": "Empty when there are no more." }),
}).annotate({ "identifier": "v1ListTripsResponse" });
export type V1ErrorBody = typeof V1ErrorBody.Type;
export const V1ErrorBody = Schema.Struct({
  "error": Schema.Struct({
    "code": ErrorCode,
    "message": Schema.String.annotate({
      "description":
        "For a human reading a log. Deliberately vague for anything internal — the\ndetail stays in the trace rather than travelling to a browser.",
    }),
  }),
}).annotate({
  "description":
    "The one shape every failure takes on the REST edge.\n\nDeclared here rather than left to grpc-gateway's default because the gateway\ndoes not use that default: `rest.go` installs a custom error handler, and for\nas long as this message was absent the published document described a\n`rpcStatus` — `{code: int, message, details}` — that nothing has ever\nreturned. A generated client believed it, and would have failed to decode\nevery error the server actually sends.",
  "identifier": "v1ErrorBody",
});
export type V1CreateTripRequest = typeof V1CreateTripRequest.Type;
export const V1CreateTripRequest = Schema.Struct({
  "fareId": FareId,
  "idempotencyKey": Schema.String.annotate({
    "description":
      "Generated client-side, so a retry over a flaky connection is recognised\nrather than booked twice.\n\nThe generated TypeScript client sends it here, in the message. The gateway\nalso accepts an `Idempotency-Key` header and copies it into this field, for\ncallers that would rather describe the request than the trip — a proxy can\nread a header without parsing a body. The handler prefers the field.",
  }),
}).annotate({ "identifier": "v1CreateTripRequest" });
export type V1CreateTripResponse = typeof V1CreateTripResponse.Type;
export const V1CreateTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CreateTripResponse" });
export type V1GetTripResponse = typeof V1GetTripResponse.Type;
export const V1GetTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1GetTripResponse" });
export type V1ArriveTripResponse = typeof V1ArriveTripResponse.Type;
export const V1ArriveTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1ArriveTripResponse" });
export type TripServiceCancelTripBody = typeof TripServiceCancelTripBody.Type;
export const TripServiceCancelTripBody = Schema.Struct({ "reason": Schema.String }).annotate({
  "identifier": "TripServiceCancelTripBody",
});
export type V1CancelTripResponse = typeof V1CancelTripResponse.Type;
export const V1CancelTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CancelTripResponse" });
export type V1CompleteTripResponse = typeof V1CompleteTripResponse.Type;
export const V1CompleteTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CompleteTripResponse" });
export type V1StartTripResponse = typeof V1StartTripResponse.Type;
export const V1StartTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1StartTripResponse" });
export type V1PreviewTripRequest = typeof V1PreviewTripRequest.Type;
export const V1PreviewTripRequest = Schema.Struct({
  "pickup": Schema.Struct({
    "lat": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "lng": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
  }).annotate({
    "description":
      "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
  }),
  "dropoff": Schema.Struct({
    "lat": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "lng": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
  }).annotate({
    "description":
      "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
  }),
}).annotate({
  "description":
    "The caller is NOT a field on any request.\n\nIt arrives as gRPC metadata, put there by the gateway from a verified token.\nThis matters more now that the REST body maps straight onto the message: a\n`rider_id` field would be client-supplied, and a client that can name the\nrider can quote, book and read rides as somebody else.",
  "identifier": "v1PreviewTripRequest",
});
export type V1PreviewTripResponse = typeof V1PreviewTripResponse.Type;
export const V1PreviewTripResponse = Schema.Struct({
  "fares": Schema.Array(Schema.Struct({
    "fareId": FareId,
    "packageSlug": Schema.String.annotate({
      "description":
        "Sedan, van and so on. A string rather than an enum because the catalogue is\noperator configuration, not a protocol change.",
    }),
    "totalCents": CentsFromString,
    "surgeMultiplier": Schema.Number.annotate({
      "description":
        "The multiplier applied for demand in the pickup cell at quote time. Carried\nexplicitly so a rider can be shown why a fare is what it is.",
      "format": "double",
    }).check(Schema.isFinite().annotate({ "expected": "a finite number" })),
    "expiresAt": Schema.String.annotate({ "format": "date-time" }),
  })).annotate({ "description": "Quotes for each vehicle class, priced from the same route." }),
  "route": Schema.Struct({
    "polyline6": Schema.String.annotate({
      "description":
        "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
    }),
    "meters": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "seconds": Int64FromString,
  }).annotate({ "description": "Route is a driveable path with its cost." }),
}).annotate({ "identifier": "v1PreviewTripResponse" });
// schemas
export type ListParams = typeof ListParams.Type;
export const ListParams = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
  "status": Schema.optionalKey(Schema.String),
});
export type ListQuery = typeof ListQuery.Type;
export const ListQuery = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
  "status": Schema.optionalKey(Schema.String),
});
export type List200 = typeof List200.Type;
export const List200 = V1ListTripsResponse;
export type List400 = typeof List400.Type;
export const List400 = V1ErrorBody;
export type List401 = typeof List401.Type;
export const List401 = V1ErrorBody;
export type List403 = typeof List403.Type;
export const List403 = V1ErrorBody;
export type List404 = typeof List404.Type;
export const List404 = V1ErrorBody;
export type List409 = typeof List409.Type;
export const List409 = V1ErrorBody;
export type List429 = typeof List429.Type;
export const List429 = V1ErrorBody;
export type List500 = typeof List500.Type;
export const List500 = V1ErrorBody;
export type List501 = typeof List501.Type;
export const List501 = V1ErrorBody;
export type List503 = typeof List503.Type;
export const List503 = V1ErrorBody;
export type List504 = typeof List504.Type;
export const List504 = V1ErrorBody;
export type CreateRequestJson = typeof CreateRequestJson.Type;
export const CreateRequestJson = V1CreateTripRequest;
export type Create200 = typeof Create200.Type;
export const Create200 = V1CreateTripResponse;
export type Create400 = typeof Create400.Type;
export const Create400 = V1ErrorBody;
export type Create401 = typeof Create401.Type;
export const Create401 = V1ErrorBody;
export type Create403 = typeof Create403.Type;
export const Create403 = V1ErrorBody;
export type Create404 = typeof Create404.Type;
export const Create404 = V1ErrorBody;
export type Create409 = typeof Create409.Type;
export const Create409 = V1ErrorBody;
export type Create429 = typeof Create429.Type;
export const Create429 = V1ErrorBody;
export type Create500 = typeof Create500.Type;
export const Create500 = V1ErrorBody;
export type Create501 = typeof Create501.Type;
export const Create501 = V1ErrorBody;
export type Create503 = typeof Create503.Type;
export const Create503 = V1ErrorBody;
export type Create504 = typeof Create504.Type;
export const Create504 = V1ErrorBody;
export type GetPathParams = typeof GetPathParams.Type;
export const GetPathParams = Schema.Struct({ "tripId": TripId });
export type Get200 = typeof Get200.Type;
export const Get200 = V1GetTripResponse;
export type Get400 = typeof Get400.Type;
export const Get400 = V1ErrorBody;
export type Get401 = typeof Get401.Type;
export const Get401 = V1ErrorBody;
export type Get403 = typeof Get403.Type;
export const Get403 = V1ErrorBody;
export type Get404 = typeof Get404.Type;
export const Get404 = V1ErrorBody;
export type Get409 = typeof Get409.Type;
export const Get409 = V1ErrorBody;
export type Get429 = typeof Get429.Type;
export const Get429 = V1ErrorBody;
export type Get500 = typeof Get500.Type;
export const Get500 = V1ErrorBody;
export type Get501 = typeof Get501.Type;
export const Get501 = V1ErrorBody;
export type Get503 = typeof Get503.Type;
export const Get503 = V1ErrorBody;
export type Get504 = typeof Get504.Type;
export const Get504 = V1ErrorBody;
export type ArrivePathParams = typeof ArrivePathParams.Type;
export const ArrivePathParams = Schema.Struct({ "tripId": TripId });
export type Arrive200 = typeof Arrive200.Type;
export const Arrive200 = V1ArriveTripResponse;
export type Arrive400 = typeof Arrive400.Type;
export const Arrive400 = V1ErrorBody;
export type Arrive401 = typeof Arrive401.Type;
export const Arrive401 = V1ErrorBody;
export type Arrive403 = typeof Arrive403.Type;
export const Arrive403 = V1ErrorBody;
export type Arrive404 = typeof Arrive404.Type;
export const Arrive404 = V1ErrorBody;
export type Arrive409 = typeof Arrive409.Type;
export const Arrive409 = V1ErrorBody;
export type Arrive429 = typeof Arrive429.Type;
export const Arrive429 = V1ErrorBody;
export type Arrive500 = typeof Arrive500.Type;
export const Arrive500 = V1ErrorBody;
export type Arrive501 = typeof Arrive501.Type;
export const Arrive501 = V1ErrorBody;
export type Arrive503 = typeof Arrive503.Type;
export const Arrive503 = V1ErrorBody;
export type Arrive504 = typeof Arrive504.Type;
export const Arrive504 = V1ErrorBody;
export type CancelPathParams = typeof CancelPathParams.Type;
export const CancelPathParams = Schema.Struct({ "tripId": TripId });
export type CancelRequestJson = typeof CancelRequestJson.Type;
export const CancelRequestJson = TripServiceCancelTripBody;
export type Cancel200 = typeof Cancel200.Type;
export const Cancel200 = V1CancelTripResponse;
export type Cancel400 = typeof Cancel400.Type;
export const Cancel400 = V1ErrorBody;
export type Cancel401 = typeof Cancel401.Type;
export const Cancel401 = V1ErrorBody;
export type Cancel403 = typeof Cancel403.Type;
export const Cancel403 = V1ErrorBody;
export type Cancel404 = typeof Cancel404.Type;
export const Cancel404 = V1ErrorBody;
export type Cancel409 = typeof Cancel409.Type;
export const Cancel409 = V1ErrorBody;
export type Cancel429 = typeof Cancel429.Type;
export const Cancel429 = V1ErrorBody;
export type Cancel500 = typeof Cancel500.Type;
export const Cancel500 = V1ErrorBody;
export type Cancel501 = typeof Cancel501.Type;
export const Cancel501 = V1ErrorBody;
export type Cancel503 = typeof Cancel503.Type;
export const Cancel503 = V1ErrorBody;
export type Cancel504 = typeof Cancel504.Type;
export const Cancel504 = V1ErrorBody;
export type CompletePathParams = typeof CompletePathParams.Type;
export const CompletePathParams = Schema.Struct({ "tripId": TripId });
export type Complete200 = typeof Complete200.Type;
export const Complete200 = V1CompleteTripResponse;
export type Complete400 = typeof Complete400.Type;
export const Complete400 = V1ErrorBody;
export type Complete401 = typeof Complete401.Type;
export const Complete401 = V1ErrorBody;
export type Complete403 = typeof Complete403.Type;
export const Complete403 = V1ErrorBody;
export type Complete404 = typeof Complete404.Type;
export const Complete404 = V1ErrorBody;
export type Complete409 = typeof Complete409.Type;
export const Complete409 = V1ErrorBody;
export type Complete429 = typeof Complete429.Type;
export const Complete429 = V1ErrorBody;
export type Complete500 = typeof Complete500.Type;
export const Complete500 = V1ErrorBody;
export type Complete501 = typeof Complete501.Type;
export const Complete501 = V1ErrorBody;
export type Complete503 = typeof Complete503.Type;
export const Complete503 = V1ErrorBody;
export type Complete504 = typeof Complete504.Type;
export const Complete504 = V1ErrorBody;
export type StartPathParams = typeof StartPathParams.Type;
export const StartPathParams = Schema.Struct({ "tripId": TripId });
export type Start200 = typeof Start200.Type;
export const Start200 = V1StartTripResponse;
export type Start400 = typeof Start400.Type;
export const Start400 = V1ErrorBody;
export type Start401 = typeof Start401.Type;
export const Start401 = V1ErrorBody;
export type Start403 = typeof Start403.Type;
export const Start403 = V1ErrorBody;
export type Start404 = typeof Start404.Type;
export const Start404 = V1ErrorBody;
export type Start409 = typeof Start409.Type;
export const Start409 = V1ErrorBody;
export type Start429 = typeof Start429.Type;
export const Start429 = V1ErrorBody;
export type Start500 = typeof Start500.Type;
export const Start500 = V1ErrorBody;
export type Start501 = typeof Start501.Type;
export const Start501 = V1ErrorBody;
export type Start503 = typeof Start503.Type;
export const Start503 = V1ErrorBody;
export type Start504 = typeof Start504.Type;
export const Start504 = V1ErrorBody;
export type PreviewRequestJson = typeof PreviewRequestJson.Type;
export const PreviewRequestJson = V1PreviewTripRequest;
export type Preview200 = typeof Preview200.Type;
export const Preview200 = V1PreviewTripResponse;
export type Preview400 = typeof Preview400.Type;
export const Preview400 = V1ErrorBody;
export type Preview401 = typeof Preview401.Type;
export const Preview401 = V1ErrorBody;
export type Preview403 = typeof Preview403.Type;
export const Preview403 = V1ErrorBody;
export type Preview404 = typeof Preview404.Type;
export const Preview404 = V1ErrorBody;
export type Preview409 = typeof Preview409.Type;
export const Preview409 = V1ErrorBody;
export type Preview429 = typeof Preview429.Type;
export const Preview429 = V1ErrorBody;
export type Preview500 = typeof Preview500.Type;
export const Preview500 = V1ErrorBody;
export type Preview501 = typeof Preview501.Type;
export const Preview501 = V1ErrorBody;
export type Preview503 = typeof Preview503.Type;
export const Preview503 = V1ErrorBody;
export type Preview504 = typeof Preview504.Type;
export const Preview504 = V1ErrorBody;

class TripsGroup extends HttpApiGroup.make("trips")
  .add(
    HttpApiEndpoint.get("list", "/v1/trips", {
      query: ListQuery,
      success: List200,
      error: [
        List400.pipe(HttpApiSchema.status(400)),
        List401.pipe(HttpApiSchema.status(401)),
        List403.pipe(HttpApiSchema.status(403)),
        List404.pipe(HttpApiSchema.status(404)),
        List409.pipe(HttpApiSchema.status(409)),
        List429.pipe(HttpApiSchema.status(429)),
        List500,
        List501.pipe(HttpApiSchema.status(501)),
        List503.pipe(HttpApiSchema.status(503)),
        List504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "list")
      .annotate(
        OpenApi.Summary,
        "ListTrips is the caller's history, newest first — the rides a rider booked,\nor the rides a driver was assigned. The token decides which.",
      ),
    HttpApiEndpoint.post("create", "/v1/trips", {
      payload: CreateRequestJson,
      success: Create200,
      error: [
        Create400.pipe(HttpApiSchema.status(400)),
        Create401.pipe(HttpApiSchema.status(401)),
        Create403.pipe(HttpApiSchema.status(403)),
        Create404.pipe(HttpApiSchema.status(404)),
        Create409.pipe(HttpApiSchema.status(409)),
        Create429.pipe(HttpApiSchema.status(429)),
        Create500,
        Create501.pipe(HttpApiSchema.status(501)),
        Create503.pipe(HttpApiSchema.status(503)),
        Create504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "create")
      .annotate(
        OpenApi.Summary,
        "Create commits a previewed fare to a real trip and starts matching.",
      )
      .annotate(
        OpenApi.Description,
        "Takes an idempotency key because the caller is a browser on a phone\nnetwork: a retried request must return the original trip rather than\nbooking a second one.",
      ),
    HttpApiEndpoint.get("get", "/v1/trips/:tripId", {
      params: GetPathParams,
      success: Get200,
      error: [
        Get400.pipe(HttpApiSchema.status(400)),
        Get401.pipe(HttpApiSchema.status(401)),
        Get403.pipe(HttpApiSchema.status(403)),
        Get404.pipe(HttpApiSchema.status(404)),
        Get409.pipe(HttpApiSchema.status(409)),
        Get429.pipe(HttpApiSchema.status(429)),
        Get500,
        Get501.pipe(HttpApiSchema.status(501)),
        Get503.pipe(HttpApiSchema.status(503)),
        Get504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "get")
      .annotate(OpenApi.Summary, "Get returns a trip's current state."),
    HttpApiEndpoint.post("arrive", "/v1/trips/:tripId/arrive", {
      params: ArrivePathParams,
      success: Arrive200,
      error: [
        Arrive400.pipe(HttpApiSchema.status(400)),
        Arrive401.pipe(HttpApiSchema.status(401)),
        Arrive403.pipe(HttpApiSchema.status(403)),
        Arrive404.pipe(HttpApiSchema.status(404)),
        Arrive409.pipe(HttpApiSchema.status(409)),
        Arrive429.pipe(HttpApiSchema.status(429)),
        Arrive500,
        Arrive501.pipe(HttpApiSchema.status(501)),
        Arrive503.pipe(HttpApiSchema.status(503)),
        Arrive504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "arrive")
      .annotate(
        OpenApi.Summary,
        "ArriveTrip, StartTrip and CompleteTrip are the driver's half of the\nlifecycle: accepted → arrived → in progress → completed.",
      )
      .annotate(
        OpenApi.Description,
        "Only the driver the trip is assigned to may call them, and the trip service\nenforces that rather than the gateway, for the same reason ownership is\nenforced there on reads: only the service knows whose trip it is. A caller\nwho is not the assigned driver gets NotFound, because confirming a trip\nexists to someone who may not touch it is itself a disclosure.\n\nNo body: the trip id in the path is the whole request, and the caller is\nmetadata like everywhere else.\nArrive: the driver is at the pickup.",
      ),
    HttpApiEndpoint.post("cancel", "/v1/trips/:tripId/cancel", {
      params: CancelPathParams,
      payload: CancelRequestJson,
      success: Cancel200,
      error: [
        Cancel400.pipe(HttpApiSchema.status(400)),
        Cancel401.pipe(HttpApiSchema.status(401)),
        Cancel403.pipe(HttpApiSchema.status(403)),
        Cancel404.pipe(HttpApiSchema.status(404)),
        Cancel409.pipe(HttpApiSchema.status(409)),
        Cancel429.pipe(HttpApiSchema.status(429)),
        Cancel500,
        Cancel501.pipe(HttpApiSchema.status(501)),
        Cancel503.pipe(HttpApiSchema.status(503)),
        Cancel504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "cancel")
      .annotate(OpenApi.Summary, "Cancel ends a trip before completion.")
      .annotate(
        OpenApi.Description,
        "A custom method rather than DELETE: cancelling is a state transition that\nreturns the trip, not a deletion — the row stays, and a rider can still\nread what happened to it.",
      ),
    HttpApiEndpoint.post("complete", "/v1/trips/:tripId/complete", {
      params: CompletePathParams,
      success: Complete200,
      error: [
        Complete400.pipe(HttpApiSchema.status(400)),
        Complete401.pipe(HttpApiSchema.status(401)),
        Complete403.pipe(HttpApiSchema.status(403)),
        Complete404.pipe(HttpApiSchema.status(404)),
        Complete409.pipe(HttpApiSchema.status(409)),
        Complete429.pipe(HttpApiSchema.status(429)),
        Complete500,
        Complete501.pipe(HttpApiSchema.status(501)),
        Complete503.pipe(HttpApiSchema.status(503)),
        Complete504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "complete")
      .annotate(OpenApi.Summary, "Complete: the rider has been dropped off."),
    HttpApiEndpoint.post("start", "/v1/trips/:tripId/start", {
      params: StartPathParams,
      success: Start200,
      error: [
        Start400.pipe(HttpApiSchema.status(400)),
        Start401.pipe(HttpApiSchema.status(401)),
        Start403.pipe(HttpApiSchema.status(403)),
        Start404.pipe(HttpApiSchema.status(404)),
        Start409.pipe(HttpApiSchema.status(409)),
        Start429.pipe(HttpApiSchema.status(429)),
        Start500,
        Start501.pipe(HttpApiSchema.status(501)),
        Start503.pipe(HttpApiSchema.status(503)),
        Start504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "start")
      .annotate(OpenApi.Summary, "Start: the rider is in the car."),
    HttpApiEndpoint.post("preview", "/v1/trips:preview", {
      payload: PreviewRequestJson,
      success: Preview200,
      error: [
        Preview400.pipe(HttpApiSchema.status(400)),
        Preview401.pipe(HttpApiSchema.status(401)),
        Preview403.pipe(HttpApiSchema.status(403)),
        Preview404.pipe(HttpApiSchema.status(404)),
        Preview409.pipe(HttpApiSchema.status(409)),
        Preview429.pipe(HttpApiSchema.status(429)),
        Preview500,
        Preview501.pipe(HttpApiSchema.status(501)),
        Preview503.pipe(HttpApiSchema.status(503)),
        Preview504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "preview")
      .annotate(
        OpenApi.Summary,
        "Preview quotes a trip without committing to it. Read-only, so a rider\ndragging a pin can call it repeatedly.",
      )
      .annotate(
        OpenApi.Description,
        "POST rather than GET despite being read-only: the request carries two\ncoordinate pairs, and a GET would put a rider's exact pickup and dropoff\ninto every access log and browser history along the way.",
      ),
  )
{}

export class SurgeApi extends HttpApi.make("SurgeApi")
  .annotate(OpenApi.Title, "trip.proto")
  .annotate(OpenApi.Version, "version not set")
  .add(TripsGroup)
{}
