/**
 * GENERATED — do not edit. Run `make proto`.
 *
 * The Go API, as this codebase consumes it. Generated by
 * `@effect/openapi-generator` from the OpenAPI document grpc-gateway emits from
 * `proto/*.proto`, which is the single source of truth for the gRPC service,
 * the REST reverse proxy, the published spec and this file.
 *
 * `HttpApiBuilder` is never used: no TypeScript implements this. What it gives
 * the browser is a typed client and runtime decoding at the boundary, which is
 * the difference between a wrong response failing here with a readable error and
 * failing three components later as `undefined is not an object`.
 *
 * `scripts/generate-api-client.mjs` describes the two things the document cannot
 * say for itself — that the gateway's `EmitUnpopulated` makes every field
 * present, and that a `format` names a branded id or a 64-bit number.
 */
import * as Schema from "effect/Schema";
import {
  HttpApi,
  HttpApiEndpoint,
  HttpApiGroup,
  HttpApiSchema,
  OpenApi,
} from "effect/unstable/httpapi";
import {
  CentsFromString,
  DriverId,
  ErrorCode,
  FareId,
  Int64FromString,
  PaymentId,
  RefundId,
  RiderId,
  TripId,
  WithdrawalId,
} from "./Primitives.js";
// non-recursive definitions
export type V1GetBalanceResponse = typeof V1GetBalanceResponse.Type;
export const V1GetBalanceResponse = Schema.Struct({
  "balance": Schema.Struct({
    "availableCents": CentsFromString,
    "pendingCents": CentsFromString,
    "owedCents": CentsFromString,
    "currency": Schema.String,
    "canWithdraw": Schema.Boolean,
  }),
}).annotate({ "identifier": "v1GetBalanceResponse" });
export type V1ErrorBody = typeof V1ErrorBody.Type;
export const V1ErrorBody = Schema.Struct({
  "error": Schema.Struct({
    "code": ErrorCode,
    "message": Schema.String.annotate({
      "description":
        "For a human reading a log. Deliberately vague for anything internal — the\ndetail stays in the trace rather than travelling to a browser.",
    }),
  }),
}).annotate({
  "description":
    "The one shape every failure takes on the REST edge.\n\nDeclared here rather than left to grpc-gateway's default because the gateway\ndoes not use that default: `rest.go` installs a custom error handler, and for\nas long as this message was absent the published document described a\n`rpcStatus` — `{code: int, message, details}` — that nothing has ever\nreturned. A generated client believed it, and would have failed to decode\nevery error the server actually sends.",
  "identifier": "v1ErrorBody",
});
export type V1ListEarningsResponse = typeof V1ListEarningsResponse.Type;
export const V1ListEarningsResponse = Schema.Struct({
  "earnings": Schema.Array(Schema.Struct({
    "tripId": TripId,
    "grossCents": CentsFromString,
    "commissionCents": CentsFromString,
    "netCents": CentsFromString,
    "currency": Schema.String,
    "status": Schema.Literals([
      "EARNING_STATUS_UNSPECIFIED",
      "EARNING_STATUS_UNPAID",
      "EARNING_STATUS_TRANSFERRED",
      "EARNING_STATUS_REVERSED",
    ]).annotate({
      "description":
        " - EARNING_STATUS_UNPAID: Owed, waiting for an account that can receive it.\n - EARNING_STATUS_REVERSED: Taken back after a refund or a dispute.",
      "default": "EARNING_STATUS_UNSPECIFIED",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
  })),
  "nextPageToken": Schema.String.annotate({ "description": "Empty when there are no more." }),
  "owedCents": CentsFromString,
  "paidCents": CentsFromString,
  "currency": Schema.String,
}).annotate({ "identifier": "v1ListEarningsResponse" });
export type V1GetPaymentMethodResponse = typeof V1GetPaymentMethodResponse.Type;
export const V1GetPaymentMethodResponse = Schema.Struct({
  "saved": Schema.Boolean.annotate({
    "description":
      "False until the rider has saved a card. The card is then empty rather than\nabsent, like every unset field this API sends.",
  }),
  "card": Schema.Struct({
    "brand": Schema.String,
    "last4": Schema.String,
    "expMonth": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
    "expYear": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  }),
}).annotate({ "identifier": "v1GetPaymentMethodResponse" });
export type V1GetPayoutAccountResponse = typeof V1GetPayoutAccountResponse.Type;
export const V1GetPayoutAccountResponse = Schema.Struct({
  "account": Schema.Struct({
    "status": Schema.Literals([
      "PAYOUT_ACCOUNT_STATUS_UNSPECIFIED",
      "PAYOUT_ACCOUNT_STATUS_NOT_STARTED",
      "PAYOUT_ACCOUNT_STATUS_PENDING",
      "PAYOUT_ACCOUNT_STATUS_ACTIVE",
    ]).annotate({
      "description":
        " - PAYOUT_ACCOUNT_STATUS_NOT_STARTED: No account yet. Earnings are recorded and owed.\n - PAYOUT_ACCOUNT_STATUS_PENDING: An account that cannot receive money yet.\n - PAYOUT_ACCOUNT_STATUS_ACTIVE: Paid as trips complete.",
      "default": "PAYOUT_ACCOUNT_STATUS_UNSPECIFIED",
    }),
    "requirementsDue": Schema.Boolean.annotate({
      "description":
        "The processor is waiting on the driver for something: send them back\nthrough onboarding.",
    }),
  }),
}).annotate({ "identifier": "v1GetPayoutAccountResponse" });
export type V1StartOnboardingRequest = typeof V1StartOnboardingRequest.Type;
export const V1StartOnboardingRequest = Schema.Struct({}).annotate({
  "identifier": "v1StartOnboardingRequest",
});
export type V1StartOnboardingResponse = typeof V1StartOnboardingResponse.Type;
export const V1StartOnboardingResponse = Schema.Struct({
  "url": Schema.String.annotate({
    "description":
      "Single use and short-lived: redirect to it at once, and never send it\nanywhere else — it opens the driver's identity details to whoever follows\nit.",
  }),
}).annotate({ "identifier": "v1StartOnboardingResponse" });
export type V1CreateSetupIntentRequest = typeof V1CreateSetupIntentRequest.Type;
export const V1CreateSetupIntentRequest = Schema.Struct({}).annotate({
  "identifier": "v1CreateSetupIntentRequest",
});
export type V1CreateSetupIntentResponse = typeof V1CreateSetupIntentResponse.Type;
export const V1CreateSetupIntentResponse = Schema.Struct({
  "clientSecret": Schema.String.annotate({
    "description": "Confirms this setup and nothing else, and is handed straight to Stripe.js.",
  }),
}).annotate({ "identifier": "v1CreateSetupIntentResponse" });
export type V1GetTripPaymentResponse = typeof V1GetTripPaymentResponse.Type;
export const V1GetTripPaymentResponse = Schema.Struct({
  "payment": Schema.Struct({
    "id": PaymentId,
    "tripId": TripId,
    "status": Schema.Literals([
      "PAYMENT_STATUS_UNSPECIFIED",
      "PAYMENT_STATUS_AUTHORIZING",
      "PAYMENT_STATUS_REQUIRES_ACTION",
      "PAYMENT_STATUS_AUTHORIZED",
      "PAYMENT_STATUS_CAPTURED",
      "PAYMENT_STATUS_RELEASED",
      "PAYMENT_STATUS_FAILED",
      "PAYMENT_STATUS_REFUNDED",
    ]).annotate({
      "description": "PaymentStatus is the payment state machine, as a client sees it.",
      "default": "PAYMENT_STATUS_UNSPECIFIED",
    }),
    "amountCents": CentsFromString,
    "capturedCents": CentsFromString,
    "refundedCents": CentsFromString,
    "currency": Schema.String,
    "failureReason": Schema.String.annotate({
      "description":
        "Why a failed payment failed: no_payment_method, declined,\nauthentication_failed or expired. Empty otherwise.",
    }),
    "clientSecret": Schema.String.annotate({
      "description":
        "Set while the status is REQUIRES_ACTION, for Stripe.js to run the rider's\nauthentication step, and only for the rider. Empty otherwise.",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1GetTripPaymentResponse" });
export type PaymentsServiceRefundTripBody = typeof PaymentsServiceRefundTripBody.Type;
export const PaymentsServiceRefundTripBody = Schema.Struct({
  "amountCents": CentsFromString,
  "reason": Schema.String,
  "idempotencyKey": Schema.String,
}).annotate({ "identifier": "PaymentsServiceRefundTripBody" });
export type V1RefundTripResponse = typeof V1RefundTripResponse.Type;
export const V1RefundTripResponse = Schema.Struct({
  "refund": Schema.Struct({
    "id": RefundId,
    "tripId": TripId,
    "amountCents": CentsFromString,
    "driverCents": CentsFromString,
    "currency": Schema.String,
    "reason": Schema.String,
    "reversal": Schema.Literals([
      "REFUND_REVERSAL_UNSPECIFIED",
      "REFUND_REVERSAL_NONE",
      "REFUND_REVERSAL_DEDUCTED",
      "REFUND_REVERSAL_REVERSED",
      "REFUND_REVERSAL_FAILED",
    ]).annotate({
      "description":
        "RefundReversal is how a refund took the driver's share back.\n\n - REFUND_REVERSAL_NONE: Nothing was earned on the trip.\n - REFUND_REVERSAL_DEDUCTED: Not yet paid out: the driver is owed less.\n - REFUND_REVERSAL_REVERSED: Taken back from the driver's balance.\n - REFUND_REVERSAL_FAILED: The driver's balance could not cover it; the platform carries it.",
      "default": "REFUND_REVERSAL_UNSPECIFIED",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "status": Schema.Literals([
      "REFUND_STATUS_UNSPECIFIED",
      "REFUND_STATUS_SUCCEEDED",
      "REFUND_STATUS_FAILED",
    ]).annotate({
      "description":
        "RefundStatus is whether a refund reached the rider.\n\n - REFUND_STATUS_FAILED: It could not be delivered. The money is back with the platform, the\npayment is refundable again, and the rider must be repaid another way.",
      "default": "REFUND_STATUS_UNSPECIFIED",
    }),
    "failureReason": Schema.String.annotate({
      "description":
        "Why a failed refund failed, in the processor's words: a closed card, a\nrefusing bank.",
    }),
  }),
  "payment": Schema.Struct({
    "id": PaymentId,
    "tripId": TripId,
    "status": Schema.Literals([
      "PAYMENT_STATUS_UNSPECIFIED",
      "PAYMENT_STATUS_AUTHORIZING",
      "PAYMENT_STATUS_REQUIRES_ACTION",
      "PAYMENT_STATUS_AUTHORIZED",
      "PAYMENT_STATUS_CAPTURED",
      "PAYMENT_STATUS_RELEASED",
      "PAYMENT_STATUS_FAILED",
      "PAYMENT_STATUS_REFUNDED",
    ]).annotate({
      "description": "PaymentStatus is the payment state machine, as a client sees it.",
      "default": "PAYMENT_STATUS_UNSPECIFIED",
    }),
    "amountCents": CentsFromString,
    "capturedCents": CentsFromString,
    "refundedCents": CentsFromString,
    "currency": Schema.String,
    "failureReason": Schema.String.annotate({
      "description":
        "Why a failed payment failed: no_payment_method, declined,\nauthentication_failed or expired. Empty otherwise.",
    }),
    "clientSecret": Schema.String.annotate({
      "description":
        "Set while the status is REQUIRES_ACTION, for Stripe.js to run the rider's\nauthentication step, and only for the rider. Empty otherwise.",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1RefundTripResponse" });
export type V1ListWithdrawalsResponse = typeof V1ListWithdrawalsResponse.Type;
export const V1ListWithdrawalsResponse = Schema.Struct({
  "withdrawals": Schema.Array(Schema.Struct({
    "id": WithdrawalId,
    "amountCents": CentsFromString,
    "currency": Schema.String,
    "status": Schema.Literals([
      "WITHDRAWAL_STATUS_UNSPECIFIED",
      "WITHDRAWAL_STATUS_REQUESTED",
      "WITHDRAWAL_STATUS_IN_TRANSIT",
      "WITHDRAWAL_STATUS_PAID",
      "WITHDRAWAL_STATUS_FAILED",
    ]).annotate({ "default": "WITHDRAWAL_STATUS_UNSPECIFIED" }),
    "failureReason": Schema.String.annotate({
      "description": "Why a failed withdrawal failed, in the processor's words.",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  })),
  "nextPageToken": Schema.String,
}).annotate({ "identifier": "v1ListWithdrawalsResponse" });
export type V1CreateWithdrawalRequest = typeof V1CreateWithdrawalRequest.Type;
export const V1CreateWithdrawalRequest = Schema.Struct({
  "amountCents": CentsFromString,
  "idempotencyKey": Schema.String.annotate({
    "description": "Generated client-side. The gateway also accepts an Idempotency-Key header.",
  }),
}).annotate({ "identifier": "v1CreateWithdrawalRequest" });
export type V1CreateWithdrawalResponse = typeof V1CreateWithdrawalResponse.Type;
export const V1CreateWithdrawalResponse = Schema.Struct({
  "withdrawal": Schema.Struct({
    "id": WithdrawalId,
    "amountCents": CentsFromString,
    "currency": Schema.String,
    "status": Schema.Literals([
      "WITHDRAWAL_STATUS_UNSPECIFIED",
      "WITHDRAWAL_STATUS_REQUESTED",
      "WITHDRAWAL_STATUS_IN_TRANSIT",
      "WITHDRAWAL_STATUS_PAID",
      "WITHDRAWAL_STATUS_FAILED",
    ]).annotate({ "default": "WITHDRAWAL_STATUS_UNSPECIFIED" }),
    "failureReason": Schema.String.annotate({
      "description": "Why a failed withdrawal failed, in the processor's words.",
    }),
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CreateWithdrawalResponse" });
export type V1GetSimulatorResponse = typeof V1GetSimulatorResponse.Type;
export const V1GetSimulatorResponse = Schema.Struct({
  "simulator": Schema.Struct({
    "drivers": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
    "running": Schema.Number.annotate({
      "description":
        "Running is how many driver goroutines are actually up, which lags\n`drivers` for a moment after a rescale.",
      "format": "int32",
    }).check(Schema.isInt().annotate({ "expected": "an integer" })),
    "pingsTotal": Int64FromString,
    "pingIntervalMs": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
    "targetPingsPerSecond": Schema.Number.annotate({
      "description": "Drivers divided by the interval: ingest's load, stated.",
      "format": "double",
    }).check(Schema.isFinite().annotate({ "expected": "a finite number" })),
  }),
}).annotate({ "identifier": "v1GetSimulatorResponse" });
export type V1ConfigureSimulatorRequest = typeof V1ConfigureSimulatorRequest.Type;
export const V1ConfigureSimulatorRequest = Schema.Struct({
  "drivers": Schema.Number.annotate({ "format": "int32" }).check(
    Schema.isInt().annotate({ "expected": "an integer" }),
  ),
  "pingIntervalMs": Schema.Number.annotate({ "format": "int32" }).check(
    Schema.isInt().annotate({ "expected": "an integer" }),
  ),
}).annotate({ "identifier": "v1ConfigureSimulatorRequest" });
export type V1ConfigureSimulatorResponse = typeof V1ConfigureSimulatorResponse.Type;
export const V1ConfigureSimulatorResponse = Schema.Struct({
  "simulator": Schema.Struct({
    "drivers": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
    "running": Schema.Number.annotate({
      "description":
        "Running is how many driver goroutines are actually up, which lags\n`drivers` for a moment after a rescale.",
      "format": "int32",
    }).check(Schema.isInt().annotate({ "expected": "an integer" })),
    "pingsTotal": Int64FromString,
    "pingIntervalMs": Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
    "targetPingsPerSecond": Schema.Number.annotate({
      "description": "Drivers divided by the interval: ingest's load, stated.",
      "format": "double",
    }).check(Schema.isFinite().annotate({ "expected": "a finite number" })),
  }),
}).annotate({ "identifier": "v1ConfigureSimulatorResponse" });
export type V1ListTripsResponse = typeof V1ListTripsResponse.Type;
export const V1ListTripsResponse = Schema.Struct({
  "trips": Schema.Array(Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  })),
  "nextPageToken": Schema.String.annotate({ "description": "Empty when there are no more." }),
}).annotate({ "identifier": "v1ListTripsResponse" });
export type V1CreateTripRequest = typeof V1CreateTripRequest.Type;
export const V1CreateTripRequest = Schema.Struct({
  "fareId": FareId,
  "idempotencyKey": Schema.String.annotate({
    "description":
      "Generated client-side, so a retry over a flaky connection is recognised\nrather than booked twice.\n\nThe generated TypeScript client sends it here, in the message. The gateway\nalso accepts an `Idempotency-Key` header and copies it into this field, for\ncallers that would rather describe the request than the trip — a proxy can\nread a header without parsing a body. The handler prefers the field.",
  }),
}).annotate({ "identifier": "v1CreateTripRequest" });
export type V1CreateTripResponse = typeof V1CreateTripResponse.Type;
export const V1CreateTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CreateTripResponse" });
export type V1GetTripResponse = typeof V1GetTripResponse.Type;
export const V1GetTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1GetTripResponse" });
export type V1ArriveTripResponse = typeof V1ArriveTripResponse.Type;
export const V1ArriveTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1ArriveTripResponse" });
export type TripServiceCancelTripBody = typeof TripServiceCancelTripBody.Type;
export const TripServiceCancelTripBody = Schema.Struct({ "reason": Schema.String }).annotate({
  "identifier": "TripServiceCancelTripBody",
});
export type V1CancelTripResponse = typeof V1CancelTripResponse.Type;
export const V1CancelTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CancelTripResponse" });
export type V1CompleteTripResponse = typeof V1CompleteTripResponse.Type;
export const V1CompleteTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1CompleteTripResponse" });
export type V1StartTripResponse = typeof V1StartTripResponse.Type;
export const V1StartTripResponse = Schema.Struct({
  "trip": Schema.Struct({
    "id": TripId,
    "riderId": RiderId,
    "driverId": DriverId,
    "status": Schema.Literals([
      "TRIP_STATUS_UNSPECIFIED",
      "TRIP_STATUS_REQUESTED",
      "TRIP_STATUS_OFFERED",
      "TRIP_STATUS_ACCEPTED",
      "TRIP_STATUS_ARRIVED",
      "TRIP_STATUS_IN_PROGRESS",
      "TRIP_STATUS_COMPLETED",
      "TRIP_STATUS_CANCELLED",
      "TRIP_STATUS_UNMATCHED",
      "TRIP_STATUS_PAYMENT_PENDING",
    ]).annotate({
      "description":
        "TripStatus is the state machine, and the wire is the place it is written\ndown once. UNSPECIFIED is reserved by convention so an unset field is not\nsilently a valid state.\n\n - TRIP_STATUS_UNMATCHED: No driver was found before the request expired. Distinct from cancelled:\nnobody chose it, and the rider should be offered a retry rather than an\napology.\n - TRIP_STATUS_PAYMENT_PENDING: Waiting for the fare to be held on the rider's card. Nobody is dispatched to\na ride that cannot be paid for: payments answers within about a second, or\nthe trip is cancelled with the reason payment_failed. Numbered last rather\nthan first because enum numbers are the wire, and renumbering REQUESTED\nwould change what every stored and in-flight 1 means.",
      "default": "TRIP_STATUS_UNSPECIFIED",
    }),
    "pickup": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "dropoff": Schema.Struct({
      "lat": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "lng": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
    }).annotate({
      "description":
        "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
    }),
    "route": Schema.Struct({
      "polyline6": Schema.String.annotate({
        "description":
          "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
      }),
      "meters": Schema.Number.annotate({ "format": "double" }).check(
        Schema.isFinite().annotate({ "expected": "a finite number" }),
      ),
      "seconds": Int64FromString,
    }).annotate({ "description": "Route is a driveable path with its cost." }),
    "totalCents": CentsFromString,
    "createdAt": Schema.String.annotate({ "format": "date-time" }),
    "updatedAt": Schema.String.annotate({ "format": "date-time" }),
  }),
}).annotate({ "identifier": "v1StartTripResponse" });
export type V1PreviewTripRequest = typeof V1PreviewTripRequest.Type;
export const V1PreviewTripRequest = Schema.Struct({
  "pickup": Schema.Struct({
    "lat": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "lng": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
  }).annotate({
    "description":
      "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
  }),
  "dropoff": Schema.Struct({
    "lat": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "lng": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
  }).annotate({
    "description":
      "Coordinate is WGS84. `lng` rather than `lon`, matching H3, Valhalla and the\nrest of this codebase — one spelling everywhere is worth more than any\nargument about which.",
  }),
}).annotate({
  "description":
    "The caller is NOT a field on any request.\n\nIt arrives as gRPC metadata, put there by the gateway from a verified token.\nThis matters more now that the REST body maps straight onto the message: a\n`rider_id` field would be client-supplied, and a client that can name the\nrider can quote, book and read rides as somebody else.",
  "identifier": "v1PreviewTripRequest",
});
export type V1PreviewTripResponse = typeof V1PreviewTripResponse.Type;
export const V1PreviewTripResponse = Schema.Struct({
  "fares": Schema.Array(Schema.Struct({
    "fareId": FareId,
    "packageSlug": Schema.String.annotate({
      "description":
        "Sedan, van and so on. A string rather than an enum because the catalogue is\noperator configuration, not a protocol change.",
    }),
    "totalCents": CentsFromString,
    "surgeMultiplier": Schema.Number.annotate({
      "description":
        "The multiplier applied for demand in the pickup cell at quote time. Carried\nexplicitly so a rider can be shown why a fare is what it is.",
      "format": "double",
    }).check(Schema.isFinite().annotate({ "expected": "a finite number" })),
    "expiresAt": Schema.String.annotate({ "format": "date-time" }),
  })).annotate({ "description": "Quotes for each vehicle class, priced from the same route." }),
  "route": Schema.Struct({
    "polyline6": Schema.String.annotate({
      "description":
        "Polyline encoded at precision 6, as Valhalla emits it. Not a repeated\nCoordinate: a city route is hundreds of points, and the encoded form is\nroughly a tenth the size on a connection a phone is paying for.",
    }),
    "meters": Schema.Number.annotate({ "format": "double" }).check(
      Schema.isFinite().annotate({ "expected": "a finite number" }),
    ),
    "seconds": Int64FromString,
  }).annotate({ "description": "Route is a driveable path with its cost." }),
}).annotate({ "identifier": "v1PreviewTripResponse" });
// schemas
export type PaymentsGetBalance200 = typeof PaymentsGetBalance200.Type;
export const PaymentsGetBalance200 = V1GetBalanceResponse;
export type PaymentsGetBalance400 = typeof PaymentsGetBalance400.Type;
export const PaymentsGetBalance400 = V1ErrorBody;
export type PaymentsGetBalance401 = typeof PaymentsGetBalance401.Type;
export const PaymentsGetBalance401 = V1ErrorBody;
export type PaymentsGetBalance403 = typeof PaymentsGetBalance403.Type;
export const PaymentsGetBalance403 = V1ErrorBody;
export type PaymentsGetBalance404 = typeof PaymentsGetBalance404.Type;
export const PaymentsGetBalance404 = V1ErrorBody;
export type PaymentsGetBalance409 = typeof PaymentsGetBalance409.Type;
export const PaymentsGetBalance409 = V1ErrorBody;
export type PaymentsGetBalance429 = typeof PaymentsGetBalance429.Type;
export const PaymentsGetBalance429 = V1ErrorBody;
export type PaymentsGetBalance500 = typeof PaymentsGetBalance500.Type;
export const PaymentsGetBalance500 = V1ErrorBody;
export type PaymentsGetBalance501 = typeof PaymentsGetBalance501.Type;
export const PaymentsGetBalance501 = V1ErrorBody;
export type PaymentsGetBalance503 = typeof PaymentsGetBalance503.Type;
export const PaymentsGetBalance503 = V1ErrorBody;
export type PaymentsGetBalance504 = typeof PaymentsGetBalance504.Type;
export const PaymentsGetBalance504 = V1ErrorBody;
export type PaymentsListEarningsParams = typeof PaymentsListEarningsParams.Type;
export const PaymentsListEarningsParams = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
});
export type PaymentsListEarningsQuery = typeof PaymentsListEarningsQuery.Type;
export const PaymentsListEarningsQuery = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
});
export type PaymentsListEarnings200 = typeof PaymentsListEarnings200.Type;
export const PaymentsListEarnings200 = V1ListEarningsResponse;
export type PaymentsListEarnings400 = typeof PaymentsListEarnings400.Type;
export const PaymentsListEarnings400 = V1ErrorBody;
export type PaymentsListEarnings401 = typeof PaymentsListEarnings401.Type;
export const PaymentsListEarnings401 = V1ErrorBody;
export type PaymentsListEarnings403 = typeof PaymentsListEarnings403.Type;
export const PaymentsListEarnings403 = V1ErrorBody;
export type PaymentsListEarnings404 = typeof PaymentsListEarnings404.Type;
export const PaymentsListEarnings404 = V1ErrorBody;
export type PaymentsListEarnings409 = typeof PaymentsListEarnings409.Type;
export const PaymentsListEarnings409 = V1ErrorBody;
export type PaymentsListEarnings429 = typeof PaymentsListEarnings429.Type;
export const PaymentsListEarnings429 = V1ErrorBody;
export type PaymentsListEarnings500 = typeof PaymentsListEarnings500.Type;
export const PaymentsListEarnings500 = V1ErrorBody;
export type PaymentsListEarnings501 = typeof PaymentsListEarnings501.Type;
export const PaymentsListEarnings501 = V1ErrorBody;
export type PaymentsListEarnings503 = typeof PaymentsListEarnings503.Type;
export const PaymentsListEarnings503 = V1ErrorBody;
export type PaymentsListEarnings504 = typeof PaymentsListEarnings504.Type;
export const PaymentsListEarnings504 = V1ErrorBody;
export type PaymentsGetMethod200 = typeof PaymentsGetMethod200.Type;
export const PaymentsGetMethod200 = V1GetPaymentMethodResponse;
export type PaymentsGetMethod400 = typeof PaymentsGetMethod400.Type;
export const PaymentsGetMethod400 = V1ErrorBody;
export type PaymentsGetMethod401 = typeof PaymentsGetMethod401.Type;
export const PaymentsGetMethod401 = V1ErrorBody;
export type PaymentsGetMethod403 = typeof PaymentsGetMethod403.Type;
export const PaymentsGetMethod403 = V1ErrorBody;
export type PaymentsGetMethod404 = typeof PaymentsGetMethod404.Type;
export const PaymentsGetMethod404 = V1ErrorBody;
export type PaymentsGetMethod409 = typeof PaymentsGetMethod409.Type;
export const PaymentsGetMethod409 = V1ErrorBody;
export type PaymentsGetMethod429 = typeof PaymentsGetMethod429.Type;
export const PaymentsGetMethod429 = V1ErrorBody;
export type PaymentsGetMethod500 = typeof PaymentsGetMethod500.Type;
export const PaymentsGetMethod500 = V1ErrorBody;
export type PaymentsGetMethod501 = typeof PaymentsGetMethod501.Type;
export const PaymentsGetMethod501 = V1ErrorBody;
export type PaymentsGetMethod503 = typeof PaymentsGetMethod503.Type;
export const PaymentsGetMethod503 = V1ErrorBody;
export type PaymentsGetMethod504 = typeof PaymentsGetMethod504.Type;
export const PaymentsGetMethod504 = V1ErrorBody;
export type PaymentsGetPayoutAccount200 = typeof PaymentsGetPayoutAccount200.Type;
export const PaymentsGetPayoutAccount200 = V1GetPayoutAccountResponse;
export type PaymentsGetPayoutAccount400 = typeof PaymentsGetPayoutAccount400.Type;
export const PaymentsGetPayoutAccount400 = V1ErrorBody;
export type PaymentsGetPayoutAccount401 = typeof PaymentsGetPayoutAccount401.Type;
export const PaymentsGetPayoutAccount401 = V1ErrorBody;
export type PaymentsGetPayoutAccount403 = typeof PaymentsGetPayoutAccount403.Type;
export const PaymentsGetPayoutAccount403 = V1ErrorBody;
export type PaymentsGetPayoutAccount404 = typeof PaymentsGetPayoutAccount404.Type;
export const PaymentsGetPayoutAccount404 = V1ErrorBody;
export type PaymentsGetPayoutAccount409 = typeof PaymentsGetPayoutAccount409.Type;
export const PaymentsGetPayoutAccount409 = V1ErrorBody;
export type PaymentsGetPayoutAccount429 = typeof PaymentsGetPayoutAccount429.Type;
export const PaymentsGetPayoutAccount429 = V1ErrorBody;
export type PaymentsGetPayoutAccount500 = typeof PaymentsGetPayoutAccount500.Type;
export const PaymentsGetPayoutAccount500 = V1ErrorBody;
export type PaymentsGetPayoutAccount501 = typeof PaymentsGetPayoutAccount501.Type;
export const PaymentsGetPayoutAccount501 = V1ErrorBody;
export type PaymentsGetPayoutAccount503 = typeof PaymentsGetPayoutAccount503.Type;
export const PaymentsGetPayoutAccount503 = V1ErrorBody;
export type PaymentsGetPayoutAccount504 = typeof PaymentsGetPayoutAccount504.Type;
export const PaymentsGetPayoutAccount504 = V1ErrorBody;
export type PaymentsStartOnboardingRequestJson = typeof PaymentsStartOnboardingRequestJson.Type;
export const PaymentsStartOnboardingRequestJson = V1StartOnboardingRequest;
export type PaymentsStartOnboarding200 = typeof PaymentsStartOnboarding200.Type;
export const PaymentsStartOnboarding200 = V1StartOnboardingResponse;
export type PaymentsStartOnboarding400 = typeof PaymentsStartOnboarding400.Type;
export const PaymentsStartOnboarding400 = V1ErrorBody;
export type PaymentsStartOnboarding401 = typeof PaymentsStartOnboarding401.Type;
export const PaymentsStartOnboarding401 = V1ErrorBody;
export type PaymentsStartOnboarding403 = typeof PaymentsStartOnboarding403.Type;
export const PaymentsStartOnboarding403 = V1ErrorBody;
export type PaymentsStartOnboarding404 = typeof PaymentsStartOnboarding404.Type;
export const PaymentsStartOnboarding404 = V1ErrorBody;
export type PaymentsStartOnboarding409 = typeof PaymentsStartOnboarding409.Type;
export const PaymentsStartOnboarding409 = V1ErrorBody;
export type PaymentsStartOnboarding429 = typeof PaymentsStartOnboarding429.Type;
export const PaymentsStartOnboarding429 = V1ErrorBody;
export type PaymentsStartOnboarding500 = typeof PaymentsStartOnboarding500.Type;
export const PaymentsStartOnboarding500 = V1ErrorBody;
export type PaymentsStartOnboarding501 = typeof PaymentsStartOnboarding501.Type;
export const PaymentsStartOnboarding501 = V1ErrorBody;
export type PaymentsStartOnboarding503 = typeof PaymentsStartOnboarding503.Type;
export const PaymentsStartOnboarding503 = V1ErrorBody;
export type PaymentsStartOnboarding504 = typeof PaymentsStartOnboarding504.Type;
export const PaymentsStartOnboarding504 = V1ErrorBody;
export type PaymentsCreateSetupIntentRequestJson = typeof PaymentsCreateSetupIntentRequestJson.Type;
export const PaymentsCreateSetupIntentRequestJson = V1CreateSetupIntentRequest;
export type PaymentsCreateSetupIntent200 = typeof PaymentsCreateSetupIntent200.Type;
export const PaymentsCreateSetupIntent200 = V1CreateSetupIntentResponse;
export type PaymentsCreateSetupIntent400 = typeof PaymentsCreateSetupIntent400.Type;
export const PaymentsCreateSetupIntent400 = V1ErrorBody;
export type PaymentsCreateSetupIntent401 = typeof PaymentsCreateSetupIntent401.Type;
export const PaymentsCreateSetupIntent401 = V1ErrorBody;
export type PaymentsCreateSetupIntent403 = typeof PaymentsCreateSetupIntent403.Type;
export const PaymentsCreateSetupIntent403 = V1ErrorBody;
export type PaymentsCreateSetupIntent404 = typeof PaymentsCreateSetupIntent404.Type;
export const PaymentsCreateSetupIntent404 = V1ErrorBody;
export type PaymentsCreateSetupIntent409 = typeof PaymentsCreateSetupIntent409.Type;
export const PaymentsCreateSetupIntent409 = V1ErrorBody;
export type PaymentsCreateSetupIntent429 = typeof PaymentsCreateSetupIntent429.Type;
export const PaymentsCreateSetupIntent429 = V1ErrorBody;
export type PaymentsCreateSetupIntent500 = typeof PaymentsCreateSetupIntent500.Type;
export const PaymentsCreateSetupIntent500 = V1ErrorBody;
export type PaymentsCreateSetupIntent501 = typeof PaymentsCreateSetupIntent501.Type;
export const PaymentsCreateSetupIntent501 = V1ErrorBody;
export type PaymentsCreateSetupIntent503 = typeof PaymentsCreateSetupIntent503.Type;
export const PaymentsCreateSetupIntent503 = V1ErrorBody;
export type PaymentsCreateSetupIntent504 = typeof PaymentsCreateSetupIntent504.Type;
export const PaymentsCreateSetupIntent504 = V1ErrorBody;
export type PaymentsGetForTripPathParams = typeof PaymentsGetForTripPathParams.Type;
export const PaymentsGetForTripPathParams = Schema.Struct({ "tripId": TripId });
export type PaymentsGetForTrip200 = typeof PaymentsGetForTrip200.Type;
export const PaymentsGetForTrip200 = V1GetTripPaymentResponse;
export type PaymentsGetForTrip400 = typeof PaymentsGetForTrip400.Type;
export const PaymentsGetForTrip400 = V1ErrorBody;
export type PaymentsGetForTrip401 = typeof PaymentsGetForTrip401.Type;
export const PaymentsGetForTrip401 = V1ErrorBody;
export type PaymentsGetForTrip403 = typeof PaymentsGetForTrip403.Type;
export const PaymentsGetForTrip403 = V1ErrorBody;
export type PaymentsGetForTrip404 = typeof PaymentsGetForTrip404.Type;
export const PaymentsGetForTrip404 = V1ErrorBody;
export type PaymentsGetForTrip409 = typeof PaymentsGetForTrip409.Type;
export const PaymentsGetForTrip409 = V1ErrorBody;
export type PaymentsGetForTrip429 = typeof PaymentsGetForTrip429.Type;
export const PaymentsGetForTrip429 = V1ErrorBody;
export type PaymentsGetForTrip500 = typeof PaymentsGetForTrip500.Type;
export const PaymentsGetForTrip500 = V1ErrorBody;
export type PaymentsGetForTrip501 = typeof PaymentsGetForTrip501.Type;
export const PaymentsGetForTrip501 = V1ErrorBody;
export type PaymentsGetForTrip503 = typeof PaymentsGetForTrip503.Type;
export const PaymentsGetForTrip503 = V1ErrorBody;
export type PaymentsGetForTrip504 = typeof PaymentsGetForTrip504.Type;
export const PaymentsGetForTrip504 = V1ErrorBody;
export type PaymentsRefundPathParams = typeof PaymentsRefundPathParams.Type;
export const PaymentsRefundPathParams = Schema.Struct({ "tripId": TripId });
export type PaymentsRefundRequestJson = typeof PaymentsRefundRequestJson.Type;
export const PaymentsRefundRequestJson = PaymentsServiceRefundTripBody;
export type PaymentsRefund200 = typeof PaymentsRefund200.Type;
export const PaymentsRefund200 = V1RefundTripResponse;
export type PaymentsRefund400 = typeof PaymentsRefund400.Type;
export const PaymentsRefund400 = V1ErrorBody;
export type PaymentsRefund401 = typeof PaymentsRefund401.Type;
export const PaymentsRefund401 = V1ErrorBody;
export type PaymentsRefund403 = typeof PaymentsRefund403.Type;
export const PaymentsRefund403 = V1ErrorBody;
export type PaymentsRefund404 = typeof PaymentsRefund404.Type;
export const PaymentsRefund404 = V1ErrorBody;
export type PaymentsRefund409 = typeof PaymentsRefund409.Type;
export const PaymentsRefund409 = V1ErrorBody;
export type PaymentsRefund429 = typeof PaymentsRefund429.Type;
export const PaymentsRefund429 = V1ErrorBody;
export type PaymentsRefund500 = typeof PaymentsRefund500.Type;
export const PaymentsRefund500 = V1ErrorBody;
export type PaymentsRefund501 = typeof PaymentsRefund501.Type;
export const PaymentsRefund501 = V1ErrorBody;
export type PaymentsRefund503 = typeof PaymentsRefund503.Type;
export const PaymentsRefund503 = V1ErrorBody;
export type PaymentsRefund504 = typeof PaymentsRefund504.Type;
export const PaymentsRefund504 = V1ErrorBody;
export type PaymentsListWithdrawalsParams = typeof PaymentsListWithdrawalsParams.Type;
export const PaymentsListWithdrawalsParams = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
});
export type PaymentsListWithdrawalsQuery = typeof PaymentsListWithdrawalsQuery.Type;
export const PaymentsListWithdrawalsQuery = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
});
export type PaymentsListWithdrawals200 = typeof PaymentsListWithdrawals200.Type;
export const PaymentsListWithdrawals200 = V1ListWithdrawalsResponse;
export type PaymentsListWithdrawals400 = typeof PaymentsListWithdrawals400.Type;
export const PaymentsListWithdrawals400 = V1ErrorBody;
export type PaymentsListWithdrawals401 = typeof PaymentsListWithdrawals401.Type;
export const PaymentsListWithdrawals401 = V1ErrorBody;
export type PaymentsListWithdrawals403 = typeof PaymentsListWithdrawals403.Type;
export const PaymentsListWithdrawals403 = V1ErrorBody;
export type PaymentsListWithdrawals404 = typeof PaymentsListWithdrawals404.Type;
export const PaymentsListWithdrawals404 = V1ErrorBody;
export type PaymentsListWithdrawals409 = typeof PaymentsListWithdrawals409.Type;
export const PaymentsListWithdrawals409 = V1ErrorBody;
export type PaymentsListWithdrawals429 = typeof PaymentsListWithdrawals429.Type;
export const PaymentsListWithdrawals429 = V1ErrorBody;
export type PaymentsListWithdrawals500 = typeof PaymentsListWithdrawals500.Type;
export const PaymentsListWithdrawals500 = V1ErrorBody;
export type PaymentsListWithdrawals501 = typeof PaymentsListWithdrawals501.Type;
export const PaymentsListWithdrawals501 = V1ErrorBody;
export type PaymentsListWithdrawals503 = typeof PaymentsListWithdrawals503.Type;
export const PaymentsListWithdrawals503 = V1ErrorBody;
export type PaymentsListWithdrawals504 = typeof PaymentsListWithdrawals504.Type;
export const PaymentsListWithdrawals504 = V1ErrorBody;
export type PaymentsWithdrawRequestJson = typeof PaymentsWithdrawRequestJson.Type;
export const PaymentsWithdrawRequestJson = V1CreateWithdrawalRequest;
export type PaymentsWithdraw200 = typeof PaymentsWithdraw200.Type;
export const PaymentsWithdraw200 = V1CreateWithdrawalResponse;
export type PaymentsWithdraw400 = typeof PaymentsWithdraw400.Type;
export const PaymentsWithdraw400 = V1ErrorBody;
export type PaymentsWithdraw401 = typeof PaymentsWithdraw401.Type;
export const PaymentsWithdraw401 = V1ErrorBody;
export type PaymentsWithdraw403 = typeof PaymentsWithdraw403.Type;
export const PaymentsWithdraw403 = V1ErrorBody;
export type PaymentsWithdraw404 = typeof PaymentsWithdraw404.Type;
export const PaymentsWithdraw404 = V1ErrorBody;
export type PaymentsWithdraw409 = typeof PaymentsWithdraw409.Type;
export const PaymentsWithdraw409 = V1ErrorBody;
export type PaymentsWithdraw429 = typeof PaymentsWithdraw429.Type;
export const PaymentsWithdraw429 = V1ErrorBody;
export type PaymentsWithdraw500 = typeof PaymentsWithdraw500.Type;
export const PaymentsWithdraw500 = V1ErrorBody;
export type PaymentsWithdraw501 = typeof PaymentsWithdraw501.Type;
export const PaymentsWithdraw501 = V1ErrorBody;
export type PaymentsWithdraw503 = typeof PaymentsWithdraw503.Type;
export const PaymentsWithdraw503 = V1ErrorBody;
export type PaymentsWithdraw504 = typeof PaymentsWithdraw504.Type;
export const PaymentsWithdraw504 = V1ErrorBody;
export type SimulatorGet200 = typeof SimulatorGet200.Type;
export const SimulatorGet200 = V1GetSimulatorResponse;
export type SimulatorGet400 = typeof SimulatorGet400.Type;
export const SimulatorGet400 = V1ErrorBody;
export type SimulatorGet401 = typeof SimulatorGet401.Type;
export const SimulatorGet401 = V1ErrorBody;
export type SimulatorGet403 = typeof SimulatorGet403.Type;
export const SimulatorGet403 = V1ErrorBody;
export type SimulatorGet404 = typeof SimulatorGet404.Type;
export const SimulatorGet404 = V1ErrorBody;
export type SimulatorGet409 = typeof SimulatorGet409.Type;
export const SimulatorGet409 = V1ErrorBody;
export type SimulatorGet429 = typeof SimulatorGet429.Type;
export const SimulatorGet429 = V1ErrorBody;
export type SimulatorGet500 = typeof SimulatorGet500.Type;
export const SimulatorGet500 = V1ErrorBody;
export type SimulatorGet501 = typeof SimulatorGet501.Type;
export const SimulatorGet501 = V1ErrorBody;
export type SimulatorGet503 = typeof SimulatorGet503.Type;
export const SimulatorGet503 = V1ErrorBody;
export type SimulatorGet504 = typeof SimulatorGet504.Type;
export const SimulatorGet504 = V1ErrorBody;
export type SimulatorConfigureRequestJson = typeof SimulatorConfigureRequestJson.Type;
export const SimulatorConfigureRequestJson = V1ConfigureSimulatorRequest;
export type SimulatorConfigure200 = typeof SimulatorConfigure200.Type;
export const SimulatorConfigure200 = V1ConfigureSimulatorResponse;
export type SimulatorConfigure400 = typeof SimulatorConfigure400.Type;
export const SimulatorConfigure400 = V1ErrorBody;
export type SimulatorConfigure401 = typeof SimulatorConfigure401.Type;
export const SimulatorConfigure401 = V1ErrorBody;
export type SimulatorConfigure403 = typeof SimulatorConfigure403.Type;
export const SimulatorConfigure403 = V1ErrorBody;
export type SimulatorConfigure404 = typeof SimulatorConfigure404.Type;
export const SimulatorConfigure404 = V1ErrorBody;
export type SimulatorConfigure409 = typeof SimulatorConfigure409.Type;
export const SimulatorConfigure409 = V1ErrorBody;
export type SimulatorConfigure429 = typeof SimulatorConfigure429.Type;
export const SimulatorConfigure429 = V1ErrorBody;
export type SimulatorConfigure500 = typeof SimulatorConfigure500.Type;
export const SimulatorConfigure500 = V1ErrorBody;
export type SimulatorConfigure501 = typeof SimulatorConfigure501.Type;
export const SimulatorConfigure501 = V1ErrorBody;
export type SimulatorConfigure503 = typeof SimulatorConfigure503.Type;
export const SimulatorConfigure503 = V1ErrorBody;
export type SimulatorConfigure504 = typeof SimulatorConfigure504.Type;
export const SimulatorConfigure504 = V1ErrorBody;
export type TripsListParams = typeof TripsListParams.Type;
export const TripsListParams = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
  "status": Schema.optionalKey(Schema.String),
});
export type TripsListQuery = typeof TripsListQuery.Type;
export const TripsListQuery = Schema.Struct({
  "pageSize": Schema.optionalKey(
    Schema.Number.annotate({ "format": "int32" }).check(
      Schema.isInt().annotate({ "expected": "an integer" }),
    ),
  ),
  "pageToken": Schema.optionalKey(Schema.String),
  "status": Schema.optionalKey(Schema.String),
});
export type TripsList200 = typeof TripsList200.Type;
export const TripsList200 = V1ListTripsResponse;
export type TripsList400 = typeof TripsList400.Type;
export const TripsList400 = V1ErrorBody;
export type TripsList401 = typeof TripsList401.Type;
export const TripsList401 = V1ErrorBody;
export type TripsList403 = typeof TripsList403.Type;
export const TripsList403 = V1ErrorBody;
export type TripsList404 = typeof TripsList404.Type;
export const TripsList404 = V1ErrorBody;
export type TripsList409 = typeof TripsList409.Type;
export const TripsList409 = V1ErrorBody;
export type TripsList429 = typeof TripsList429.Type;
export const TripsList429 = V1ErrorBody;
export type TripsList500 = typeof TripsList500.Type;
export const TripsList500 = V1ErrorBody;
export type TripsList501 = typeof TripsList501.Type;
export const TripsList501 = V1ErrorBody;
export type TripsList503 = typeof TripsList503.Type;
export const TripsList503 = V1ErrorBody;
export type TripsList504 = typeof TripsList504.Type;
export const TripsList504 = V1ErrorBody;
export type TripsCreateRequestJson = typeof TripsCreateRequestJson.Type;
export const TripsCreateRequestJson = V1CreateTripRequest;
export type TripsCreate200 = typeof TripsCreate200.Type;
export const TripsCreate200 = V1CreateTripResponse;
export type TripsCreate400 = typeof TripsCreate400.Type;
export const TripsCreate400 = V1ErrorBody;
export type TripsCreate401 = typeof TripsCreate401.Type;
export const TripsCreate401 = V1ErrorBody;
export type TripsCreate403 = typeof TripsCreate403.Type;
export const TripsCreate403 = V1ErrorBody;
export type TripsCreate404 = typeof TripsCreate404.Type;
export const TripsCreate404 = V1ErrorBody;
export type TripsCreate409 = typeof TripsCreate409.Type;
export const TripsCreate409 = V1ErrorBody;
export type TripsCreate429 = typeof TripsCreate429.Type;
export const TripsCreate429 = V1ErrorBody;
export type TripsCreate500 = typeof TripsCreate500.Type;
export const TripsCreate500 = V1ErrorBody;
export type TripsCreate501 = typeof TripsCreate501.Type;
export const TripsCreate501 = V1ErrorBody;
export type TripsCreate503 = typeof TripsCreate503.Type;
export const TripsCreate503 = V1ErrorBody;
export type TripsCreate504 = typeof TripsCreate504.Type;
export const TripsCreate504 = V1ErrorBody;
export type TripsGetPathParams = typeof TripsGetPathParams.Type;
export const TripsGetPathParams = Schema.Struct({ "tripId": TripId });
export type TripsGet200 = typeof TripsGet200.Type;
export const TripsGet200 = V1GetTripResponse;
export type TripsGet400 = typeof TripsGet400.Type;
export const TripsGet400 = V1ErrorBody;
export type TripsGet401 = typeof TripsGet401.Type;
export const TripsGet401 = V1ErrorBody;
export type TripsGet403 = typeof TripsGet403.Type;
export const TripsGet403 = V1ErrorBody;
export type TripsGet404 = typeof TripsGet404.Type;
export const TripsGet404 = V1ErrorBody;
export type TripsGet409 = typeof TripsGet409.Type;
export const TripsGet409 = V1ErrorBody;
export type TripsGet429 = typeof TripsGet429.Type;
export const TripsGet429 = V1ErrorBody;
export type TripsGet500 = typeof TripsGet500.Type;
export const TripsGet500 = V1ErrorBody;
export type TripsGet501 = typeof TripsGet501.Type;
export const TripsGet501 = V1ErrorBody;
export type TripsGet503 = typeof TripsGet503.Type;
export const TripsGet503 = V1ErrorBody;
export type TripsGet504 = typeof TripsGet504.Type;
export const TripsGet504 = V1ErrorBody;
export type TripsArrivePathParams = typeof TripsArrivePathParams.Type;
export const TripsArrivePathParams = Schema.Struct({ "tripId": TripId });
export type TripsArrive200 = typeof TripsArrive200.Type;
export const TripsArrive200 = V1ArriveTripResponse;
export type TripsArrive400 = typeof TripsArrive400.Type;
export const TripsArrive400 = V1ErrorBody;
export type TripsArrive401 = typeof TripsArrive401.Type;
export const TripsArrive401 = V1ErrorBody;
export type TripsArrive403 = typeof TripsArrive403.Type;
export const TripsArrive403 = V1ErrorBody;
export type TripsArrive404 = typeof TripsArrive404.Type;
export const TripsArrive404 = V1ErrorBody;
export type TripsArrive409 = typeof TripsArrive409.Type;
export const TripsArrive409 = V1ErrorBody;
export type TripsArrive429 = typeof TripsArrive429.Type;
export const TripsArrive429 = V1ErrorBody;
export type TripsArrive500 = typeof TripsArrive500.Type;
export const TripsArrive500 = V1ErrorBody;
export type TripsArrive501 = typeof TripsArrive501.Type;
export const TripsArrive501 = V1ErrorBody;
export type TripsArrive503 = typeof TripsArrive503.Type;
export const TripsArrive503 = V1ErrorBody;
export type TripsArrive504 = typeof TripsArrive504.Type;
export const TripsArrive504 = V1ErrorBody;
export type TripsCancelPathParams = typeof TripsCancelPathParams.Type;
export const TripsCancelPathParams = Schema.Struct({ "tripId": TripId });
export type TripsCancelRequestJson = typeof TripsCancelRequestJson.Type;
export const TripsCancelRequestJson = TripServiceCancelTripBody;
export type TripsCancel200 = typeof TripsCancel200.Type;
export const TripsCancel200 = V1CancelTripResponse;
export type TripsCancel400 = typeof TripsCancel400.Type;
export const TripsCancel400 = V1ErrorBody;
export type TripsCancel401 = typeof TripsCancel401.Type;
export const TripsCancel401 = V1ErrorBody;
export type TripsCancel403 = typeof TripsCancel403.Type;
export const TripsCancel403 = V1ErrorBody;
export type TripsCancel404 = typeof TripsCancel404.Type;
export const TripsCancel404 = V1ErrorBody;
export type TripsCancel409 = typeof TripsCancel409.Type;
export const TripsCancel409 = V1ErrorBody;
export type TripsCancel429 = typeof TripsCancel429.Type;
export const TripsCancel429 = V1ErrorBody;
export type TripsCancel500 = typeof TripsCancel500.Type;
export const TripsCancel500 = V1ErrorBody;
export type TripsCancel501 = typeof TripsCancel501.Type;
export const TripsCancel501 = V1ErrorBody;
export type TripsCancel503 = typeof TripsCancel503.Type;
export const TripsCancel503 = V1ErrorBody;
export type TripsCancel504 = typeof TripsCancel504.Type;
export const TripsCancel504 = V1ErrorBody;
export type TripsCompletePathParams = typeof TripsCompletePathParams.Type;
export const TripsCompletePathParams = Schema.Struct({ "tripId": TripId });
export type TripsComplete200 = typeof TripsComplete200.Type;
export const TripsComplete200 = V1CompleteTripResponse;
export type TripsComplete400 = typeof TripsComplete400.Type;
export const TripsComplete400 = V1ErrorBody;
export type TripsComplete401 = typeof TripsComplete401.Type;
export const TripsComplete401 = V1ErrorBody;
export type TripsComplete403 = typeof TripsComplete403.Type;
export const TripsComplete403 = V1ErrorBody;
export type TripsComplete404 = typeof TripsComplete404.Type;
export const TripsComplete404 = V1ErrorBody;
export type TripsComplete409 = typeof TripsComplete409.Type;
export const TripsComplete409 = V1ErrorBody;
export type TripsComplete429 = typeof TripsComplete429.Type;
export const TripsComplete429 = V1ErrorBody;
export type TripsComplete500 = typeof TripsComplete500.Type;
export const TripsComplete500 = V1ErrorBody;
export type TripsComplete501 = typeof TripsComplete501.Type;
export const TripsComplete501 = V1ErrorBody;
export type TripsComplete503 = typeof TripsComplete503.Type;
export const TripsComplete503 = V1ErrorBody;
export type TripsComplete504 = typeof TripsComplete504.Type;
export const TripsComplete504 = V1ErrorBody;
export type TripsStartPathParams = typeof TripsStartPathParams.Type;
export const TripsStartPathParams = Schema.Struct({ "tripId": TripId });
export type TripsStart200 = typeof TripsStart200.Type;
export const TripsStart200 = V1StartTripResponse;
export type TripsStart400 = typeof TripsStart400.Type;
export const TripsStart400 = V1ErrorBody;
export type TripsStart401 = typeof TripsStart401.Type;
export const TripsStart401 = V1ErrorBody;
export type TripsStart403 = typeof TripsStart403.Type;
export const TripsStart403 = V1ErrorBody;
export type TripsStart404 = typeof TripsStart404.Type;
export const TripsStart404 = V1ErrorBody;
export type TripsStart409 = typeof TripsStart409.Type;
export const TripsStart409 = V1ErrorBody;
export type TripsStart429 = typeof TripsStart429.Type;
export const TripsStart429 = V1ErrorBody;
export type TripsStart500 = typeof TripsStart500.Type;
export const TripsStart500 = V1ErrorBody;
export type TripsStart501 = typeof TripsStart501.Type;
export const TripsStart501 = V1ErrorBody;
export type TripsStart503 = typeof TripsStart503.Type;
export const TripsStart503 = V1ErrorBody;
export type TripsStart504 = typeof TripsStart504.Type;
export const TripsStart504 = V1ErrorBody;
export type TripsPreviewRequestJson = typeof TripsPreviewRequestJson.Type;
export const TripsPreviewRequestJson = V1PreviewTripRequest;
export type TripsPreview200 = typeof TripsPreview200.Type;
export const TripsPreview200 = V1PreviewTripResponse;
export type TripsPreview400 = typeof TripsPreview400.Type;
export const TripsPreview400 = V1ErrorBody;
export type TripsPreview401 = typeof TripsPreview401.Type;
export const TripsPreview401 = V1ErrorBody;
export type TripsPreview403 = typeof TripsPreview403.Type;
export const TripsPreview403 = V1ErrorBody;
export type TripsPreview404 = typeof TripsPreview404.Type;
export const TripsPreview404 = V1ErrorBody;
export type TripsPreview409 = typeof TripsPreview409.Type;
export const TripsPreview409 = V1ErrorBody;
export type TripsPreview429 = typeof TripsPreview429.Type;
export const TripsPreview429 = V1ErrorBody;
export type TripsPreview500 = typeof TripsPreview500.Type;
export const TripsPreview500 = V1ErrorBody;
export type TripsPreview501 = typeof TripsPreview501.Type;
export const TripsPreview501 = V1ErrorBody;
export type TripsPreview503 = typeof TripsPreview503.Type;
export const TripsPreview503 = V1ErrorBody;
export type TripsPreview504 = typeof TripsPreview504.Type;
export const TripsPreview504 = V1ErrorBody;

class PaymentsGroup extends HttpApiGroup.make("payments")
  .add(
    HttpApiEndpoint.get("getBalance", "/v1/payments/balance", {
      success: PaymentsGetBalance200,
      error: [
        PaymentsGetBalance400.pipe(HttpApiSchema.status(400)),
        PaymentsGetBalance401.pipe(HttpApiSchema.status(401)),
        PaymentsGetBalance403.pipe(HttpApiSchema.status(403)),
        PaymentsGetBalance404.pipe(HttpApiSchema.status(404)),
        PaymentsGetBalance409.pipe(HttpApiSchema.status(409)),
        PaymentsGetBalance429.pipe(HttpApiSchema.status(429)),
        PaymentsGetBalance500,
        PaymentsGetBalance501.pipe(HttpApiSchema.status(501)),
        PaymentsGetBalance503.pipe(HttpApiSchema.status(503)),
        PaymentsGetBalance504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "getBalance")
      .annotate(
        OpenApi.Summary,
        "GetBalance is what a driver can take out now, what is on its way to their\nbalance, and what they have earned that has not reached it yet.",
      ),
    HttpApiEndpoint.get("listEarnings", "/v1/payments/earnings", {
      query: PaymentsListEarningsQuery,
      success: PaymentsListEarnings200,
      error: [
        PaymentsListEarnings400.pipe(HttpApiSchema.status(400)),
        PaymentsListEarnings401.pipe(HttpApiSchema.status(401)),
        PaymentsListEarnings403.pipe(HttpApiSchema.status(403)),
        PaymentsListEarnings404.pipe(HttpApiSchema.status(404)),
        PaymentsListEarnings409.pipe(HttpApiSchema.status(409)),
        PaymentsListEarnings429.pipe(HttpApiSchema.status(429)),
        PaymentsListEarnings500,
        PaymentsListEarnings501.pipe(HttpApiSchema.status(501)),
        PaymentsListEarnings503.pipe(HttpApiSchema.status(503)),
        PaymentsListEarnings504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "listEarnings")
      .annotate(
        OpenApi.Summary,
        "ListEarnings is a driver's share of each trip, newest first, and what is\nstill owed to them.",
      ),
    HttpApiEndpoint.get("getMethod", "/v1/payments/method", {
      success: PaymentsGetMethod200,
      error: [
        PaymentsGetMethod400.pipe(HttpApiSchema.status(400)),
        PaymentsGetMethod401.pipe(HttpApiSchema.status(401)),
        PaymentsGetMethod403.pipe(HttpApiSchema.status(403)),
        PaymentsGetMethod404.pipe(HttpApiSchema.status(404)),
        PaymentsGetMethod409.pipe(HttpApiSchema.status(409)),
        PaymentsGetMethod429.pipe(HttpApiSchema.status(429)),
        PaymentsGetMethod500,
        PaymentsGetMethod501.pipe(HttpApiSchema.status(501)),
        PaymentsGetMethod503.pipe(HttpApiSchema.status(503)),
        PaymentsGetMethod504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "getMethod")
      .annotate(OpenApi.Summary, "GetPaymentMethod is the card a rider's holds are placed on."),
    HttpApiEndpoint.get("getPayoutAccount", "/v1/payments/payout-account", {
      success: PaymentsGetPayoutAccount200,
      error: [
        PaymentsGetPayoutAccount400.pipe(HttpApiSchema.status(400)),
        PaymentsGetPayoutAccount401.pipe(HttpApiSchema.status(401)),
        PaymentsGetPayoutAccount403.pipe(HttpApiSchema.status(403)),
        PaymentsGetPayoutAccount404.pipe(HttpApiSchema.status(404)),
        PaymentsGetPayoutAccount409.pipe(HttpApiSchema.status(409)),
        PaymentsGetPayoutAccount429.pipe(HttpApiSchema.status(429)),
        PaymentsGetPayoutAccount500,
        PaymentsGetPayoutAccount501.pipe(HttpApiSchema.status(501)),
        PaymentsGetPayoutAccount503.pipe(HttpApiSchema.status(503)),
        PaymentsGetPayoutAccount504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "getPayoutAccount")
      .annotate(OpenApi.Summary, "GetPayoutAccount is whether a driver can be paid yet."),
    HttpApiEndpoint.post("startOnboarding", "/v1/payments/payout-account", {
      payload: PaymentsStartOnboardingRequestJson,
      success: PaymentsStartOnboarding200,
      error: [
        PaymentsStartOnboarding400.pipe(HttpApiSchema.status(400)),
        PaymentsStartOnboarding401.pipe(HttpApiSchema.status(401)),
        PaymentsStartOnboarding403.pipe(HttpApiSchema.status(403)),
        PaymentsStartOnboarding404.pipe(HttpApiSchema.status(404)),
        PaymentsStartOnboarding409.pipe(HttpApiSchema.status(409)),
        PaymentsStartOnboarding429.pipe(HttpApiSchema.status(429)),
        PaymentsStartOnboarding500,
        PaymentsStartOnboarding501.pipe(HttpApiSchema.status(501)),
        PaymentsStartOnboarding503.pipe(HttpApiSchema.status(503)),
        PaymentsStartOnboarding504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "startOnboarding")
      .annotate(
        OpenApi.Summary,
        "StartOnboarding creates the driver's payout account if there is none, and\nreturns a link into the processor's hosted onboarding.",
      )
      .annotate(
        OpenApi.Description,
        "The return addresses are the server's, never the caller's: a link that\nredirects wherever a request said is an open redirect with a trusted\ndomain in front of it.",
      ),
    HttpApiEndpoint.post("createSetupIntent", "/v1/payments/setup-intents", {
      payload: PaymentsCreateSetupIntentRequestJson,
      success: PaymentsCreateSetupIntent200,
      error: [
        PaymentsCreateSetupIntent400.pipe(HttpApiSchema.status(400)),
        PaymentsCreateSetupIntent401.pipe(HttpApiSchema.status(401)),
        PaymentsCreateSetupIntent403.pipe(HttpApiSchema.status(403)),
        PaymentsCreateSetupIntent404.pipe(HttpApiSchema.status(404)),
        PaymentsCreateSetupIntent409.pipe(HttpApiSchema.status(409)),
        PaymentsCreateSetupIntent429.pipe(HttpApiSchema.status(429)),
        PaymentsCreateSetupIntent500,
        PaymentsCreateSetupIntent501.pipe(HttpApiSchema.status(501)),
        PaymentsCreateSetupIntent503.pipe(HttpApiSchema.status(503)),
        PaymentsCreateSetupIntent504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "createSetupIntent")
      .annotate(
        OpenApi.Summary,
        "CreateSetupIntent starts saving a rider's card, and returns the secret the\nbrowser hands to Stripe.js to collect it.",
      ),
    HttpApiEndpoint.get("getForTrip", "/v1/payments/trips/:tripId", {
      params: PaymentsGetForTripPathParams,
      success: PaymentsGetForTrip200,
      error: [
        PaymentsGetForTrip400.pipe(HttpApiSchema.status(400)),
        PaymentsGetForTrip401.pipe(HttpApiSchema.status(401)),
        PaymentsGetForTrip403.pipe(HttpApiSchema.status(403)),
        PaymentsGetForTrip404.pipe(HttpApiSchema.status(404)),
        PaymentsGetForTrip409.pipe(HttpApiSchema.status(409)),
        PaymentsGetForTrip429.pipe(HttpApiSchema.status(429)),
        PaymentsGetForTrip500,
        PaymentsGetForTrip501.pipe(HttpApiSchema.status(501)),
        PaymentsGetForTrip503.pipe(HttpApiSchema.status(503)),
        PaymentsGetForTrip504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "getForTrip")
      .annotate(
        OpenApi.Summary,
        "GetTripPayment is what became of a trip's hold: the rider's receipt, and\nthe secret for an authentication step while one is waiting.",
      ),
    HttpApiEndpoint.post("refund", "/v1/payments/trips/:tripId/refund", {
      params: PaymentsRefundPathParams,
      payload: PaymentsRefundRequestJson,
      success: PaymentsRefund200,
      error: [
        PaymentsRefund400.pipe(HttpApiSchema.status(400)),
        PaymentsRefund401.pipe(HttpApiSchema.status(401)),
        PaymentsRefund403.pipe(HttpApiSchema.status(403)),
        PaymentsRefund404.pipe(HttpApiSchema.status(404)),
        PaymentsRefund409.pipe(HttpApiSchema.status(409)),
        PaymentsRefund429.pipe(HttpApiSchema.status(429)),
        PaymentsRefund500,
        PaymentsRefund501.pipe(HttpApiSchema.status(501)),
        PaymentsRefund503.pipe(HttpApiSchema.status(503)),
        PaymentsRefund504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "refund")
      .annotate(
        OpenApi.Summary,
        "RefundTrip gives money back to a rider, ops only, and takes the driver's\nshare of it back in proportion. An amount of zero refunds everything left.",
      ),
    HttpApiEndpoint.get("listWithdrawals", "/v1/payments/withdrawals", {
      query: PaymentsListWithdrawalsQuery,
      success: PaymentsListWithdrawals200,
      error: [
        PaymentsListWithdrawals400.pipe(HttpApiSchema.status(400)),
        PaymentsListWithdrawals401.pipe(HttpApiSchema.status(401)),
        PaymentsListWithdrawals403.pipe(HttpApiSchema.status(403)),
        PaymentsListWithdrawals404.pipe(HttpApiSchema.status(404)),
        PaymentsListWithdrawals409.pipe(HttpApiSchema.status(409)),
        PaymentsListWithdrawals429.pipe(HttpApiSchema.status(429)),
        PaymentsListWithdrawals500,
        PaymentsListWithdrawals501.pipe(HttpApiSchema.status(501)),
        PaymentsListWithdrawals503.pipe(HttpApiSchema.status(503)),
        PaymentsListWithdrawals504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "listWithdrawals")
      .annotate(OpenApi.Summary, "ListWithdrawals is a driver's withdrawals, newest first."),
    HttpApiEndpoint.post("withdraw", "/v1/payments/withdrawals", {
      payload: PaymentsWithdrawRequestJson,
      success: PaymentsWithdraw200,
      error: [
        PaymentsWithdraw400.pipe(HttpApiSchema.status(400)),
        PaymentsWithdraw401.pipe(HttpApiSchema.status(401)),
        PaymentsWithdraw403.pipe(HttpApiSchema.status(403)),
        PaymentsWithdraw404.pipe(HttpApiSchema.status(404)),
        PaymentsWithdraw409.pipe(HttpApiSchema.status(409)),
        PaymentsWithdraw429.pipe(HttpApiSchema.status(429)),
        PaymentsWithdraw500,
        PaymentsWithdraw501.pipe(HttpApiSchema.status(501)),
        PaymentsWithdraw503.pipe(HttpApiSchema.status(503)),
        PaymentsWithdraw504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "withdraw")
      .annotate(
        OpenApi.Summary,
        "CreateWithdrawal pays out from a driver's balance to their bank. An amount\nof zero withdraws everything available.",
      )
      .annotate(
        OpenApi.Description,
        "Takes an idempotency key, because it moves money and the caller is a phone:\nthe double tap and the retried request are one payout.",
      ),
  )
{}

class SimulatorGroup extends HttpApiGroup.make("simulator")
  .add(
    HttpApiEndpoint.get("get", "/v1/simulator", {
      success: SimulatorGet200,
      error: [
        SimulatorGet400.pipe(HttpApiSchema.status(400)),
        SimulatorGet401.pipe(HttpApiSchema.status(401)),
        SimulatorGet403.pipe(HttpApiSchema.status(403)),
        SimulatorGet404.pipe(HttpApiSchema.status(404)),
        SimulatorGet409.pipe(HttpApiSchema.status(409)),
        SimulatorGet429.pipe(HttpApiSchema.status(429)),
        SimulatorGet500,
        SimulatorGet501.pipe(HttpApiSchema.status(501)),
        SimulatorGet503.pipe(HttpApiSchema.status(503)),
        SimulatorGet504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "get")
      .annotate(
        OpenApi.Summary,
        "GetSimulator is the fleet's size and rate, as configured and as running.",
      ),
    HttpApiEndpoint.put("configure", "/v1/simulator", {
      payload: SimulatorConfigureRequestJson,
      success: SimulatorConfigure200,
      error: [
        SimulatorConfigure400.pipe(HttpApiSchema.status(400)),
        SimulatorConfigure401.pipe(HttpApiSchema.status(401)),
        SimulatorConfigure403.pipe(HttpApiSchema.status(403)),
        SimulatorConfigure404.pipe(HttpApiSchema.status(404)),
        SimulatorConfigure409.pipe(HttpApiSchema.status(409)),
        SimulatorConfigure429.pipe(HttpApiSchema.status(429)),
        SimulatorConfigure500,
        SimulatorConfigure501.pipe(HttpApiSchema.status(501)),
        SimulatorConfigure503.pipe(HttpApiSchema.status(503)),
        SimulatorConfigure504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "configure")
      .annotate(OpenApi.Summary, "ConfigureSimulator rescales the fleet.")
      .annotate(
        OpenApi.Description,
        "The whole desired configuration rather than a partial patch: the console\nshows both values and sends both, and a request that must carry every\nfield is one the generated client can type as exactly that.",
      ),
  )
{}

class TripsGroup extends HttpApiGroup.make("trips")
  .add(
    HttpApiEndpoint.get("list", "/v1/trips", {
      query: TripsListQuery,
      success: TripsList200,
      error: [
        TripsList400.pipe(HttpApiSchema.status(400)),
        TripsList401.pipe(HttpApiSchema.status(401)),
        TripsList403.pipe(HttpApiSchema.status(403)),
        TripsList404.pipe(HttpApiSchema.status(404)),
        TripsList409.pipe(HttpApiSchema.status(409)),
        TripsList429.pipe(HttpApiSchema.status(429)),
        TripsList500,
        TripsList501.pipe(HttpApiSchema.status(501)),
        TripsList503.pipe(HttpApiSchema.status(503)),
        TripsList504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "list")
      .annotate(
        OpenApi.Summary,
        "ListTrips is the caller's history, newest first — the rides a rider booked,\nor the rides a driver was assigned. The token decides which.",
      ),
    HttpApiEndpoint.post("create", "/v1/trips", {
      payload: TripsCreateRequestJson,
      success: TripsCreate200,
      error: [
        TripsCreate400.pipe(HttpApiSchema.status(400)),
        TripsCreate401.pipe(HttpApiSchema.status(401)),
        TripsCreate403.pipe(HttpApiSchema.status(403)),
        TripsCreate404.pipe(HttpApiSchema.status(404)),
        TripsCreate409.pipe(HttpApiSchema.status(409)),
        TripsCreate429.pipe(HttpApiSchema.status(429)),
        TripsCreate500,
        TripsCreate501.pipe(HttpApiSchema.status(501)),
        TripsCreate503.pipe(HttpApiSchema.status(503)),
        TripsCreate504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "create")
      .annotate(
        OpenApi.Summary,
        "Create commits a previewed fare to a real trip and starts matching.",
      )
      .annotate(
        OpenApi.Description,
        "Takes an idempotency key because the caller is a browser on a phone\nnetwork: a retried request must return the original trip rather than\nbooking a second one.",
      ),
    HttpApiEndpoint.get("get", "/v1/trips/:tripId", {
      params: TripsGetPathParams,
      success: TripsGet200,
      error: [
        TripsGet400.pipe(HttpApiSchema.status(400)),
        TripsGet401.pipe(HttpApiSchema.status(401)),
        TripsGet403.pipe(HttpApiSchema.status(403)),
        TripsGet404.pipe(HttpApiSchema.status(404)),
        TripsGet409.pipe(HttpApiSchema.status(409)),
        TripsGet429.pipe(HttpApiSchema.status(429)),
        TripsGet500,
        TripsGet501.pipe(HttpApiSchema.status(501)),
        TripsGet503.pipe(HttpApiSchema.status(503)),
        TripsGet504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "get")
      .annotate(OpenApi.Summary, "Get returns a trip's current state."),
    HttpApiEndpoint.post("arrive", "/v1/trips/:tripId/arrive", {
      params: TripsArrivePathParams,
      success: TripsArrive200,
      error: [
        TripsArrive400.pipe(HttpApiSchema.status(400)),
        TripsArrive401.pipe(HttpApiSchema.status(401)),
        TripsArrive403.pipe(HttpApiSchema.status(403)),
        TripsArrive404.pipe(HttpApiSchema.status(404)),
        TripsArrive409.pipe(HttpApiSchema.status(409)),
        TripsArrive429.pipe(HttpApiSchema.status(429)),
        TripsArrive500,
        TripsArrive501.pipe(HttpApiSchema.status(501)),
        TripsArrive503.pipe(HttpApiSchema.status(503)),
        TripsArrive504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "arrive")
      .annotate(
        OpenApi.Summary,
        "ArriveTrip, StartTrip and CompleteTrip are the driver's half of the\nlifecycle: accepted → arrived → in progress → completed.",
      )
      .annotate(
        OpenApi.Description,
        "Only the driver the trip is assigned to may call them, and the trip service\nenforces that rather than the gateway, for the same reason ownership is\nenforced there on reads: only the service knows whose trip it is. A caller\nwho is not the assigned driver gets NotFound, because confirming a trip\nexists to someone who may not touch it is itself a disclosure.\n\nNo body: the trip id in the path is the whole request, and the caller is\nmetadata like everywhere else.\nArrive: the driver is at the pickup.",
      ),
    HttpApiEndpoint.post("cancel", "/v1/trips/:tripId/cancel", {
      params: TripsCancelPathParams,
      payload: TripsCancelRequestJson,
      success: TripsCancel200,
      error: [
        TripsCancel400.pipe(HttpApiSchema.status(400)),
        TripsCancel401.pipe(HttpApiSchema.status(401)),
        TripsCancel403.pipe(HttpApiSchema.status(403)),
        TripsCancel404.pipe(HttpApiSchema.status(404)),
        TripsCancel409.pipe(HttpApiSchema.status(409)),
        TripsCancel429.pipe(HttpApiSchema.status(429)),
        TripsCancel500,
        TripsCancel501.pipe(HttpApiSchema.status(501)),
        TripsCancel503.pipe(HttpApiSchema.status(503)),
        TripsCancel504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "cancel")
      .annotate(OpenApi.Summary, "Cancel ends a trip before completion.")
      .annotate(
        OpenApi.Description,
        "A custom method rather than DELETE: cancelling is a state transition that\nreturns the trip, not a deletion — the row stays, and a rider can still\nread what happened to it.",
      ),
    HttpApiEndpoint.post("complete", "/v1/trips/:tripId/complete", {
      params: TripsCompletePathParams,
      success: TripsComplete200,
      error: [
        TripsComplete400.pipe(HttpApiSchema.status(400)),
        TripsComplete401.pipe(HttpApiSchema.status(401)),
        TripsComplete403.pipe(HttpApiSchema.status(403)),
        TripsComplete404.pipe(HttpApiSchema.status(404)),
        TripsComplete409.pipe(HttpApiSchema.status(409)),
        TripsComplete429.pipe(HttpApiSchema.status(429)),
        TripsComplete500,
        TripsComplete501.pipe(HttpApiSchema.status(501)),
        TripsComplete503.pipe(HttpApiSchema.status(503)),
        TripsComplete504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "complete")
      .annotate(OpenApi.Summary, "Complete: the rider has been dropped off."),
    HttpApiEndpoint.post("start", "/v1/trips/:tripId/start", {
      params: TripsStartPathParams,
      success: TripsStart200,
      error: [
        TripsStart400.pipe(HttpApiSchema.status(400)),
        TripsStart401.pipe(HttpApiSchema.status(401)),
        TripsStart403.pipe(HttpApiSchema.status(403)),
        TripsStart404.pipe(HttpApiSchema.status(404)),
        TripsStart409.pipe(HttpApiSchema.status(409)),
        TripsStart429.pipe(HttpApiSchema.status(429)),
        TripsStart500,
        TripsStart501.pipe(HttpApiSchema.status(501)),
        TripsStart503.pipe(HttpApiSchema.status(503)),
        TripsStart504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "start")
      .annotate(OpenApi.Summary, "Start: the rider is in the car."),
    HttpApiEndpoint.post("preview", "/v1/trips:preview", {
      payload: TripsPreviewRequestJson,
      success: TripsPreview200,
      error: [
        TripsPreview400.pipe(HttpApiSchema.status(400)),
        TripsPreview401.pipe(HttpApiSchema.status(401)),
        TripsPreview403.pipe(HttpApiSchema.status(403)),
        TripsPreview404.pipe(HttpApiSchema.status(404)),
        TripsPreview409.pipe(HttpApiSchema.status(409)),
        TripsPreview429.pipe(HttpApiSchema.status(429)),
        TripsPreview500,
        TripsPreview501.pipe(HttpApiSchema.status(501)),
        TripsPreview503.pipe(HttpApiSchema.status(503)),
        TripsPreview504.pipe(HttpApiSchema.status(504)),
      ],
    })
      .annotate(OpenApi.Identifier, "preview")
      .annotate(
        OpenApi.Summary,
        "Preview quotes a trip without committing to it. Read-only, so a rider\ndragging a pin can call it repeatedly.",
      )
      .annotate(
        OpenApi.Description,
        "POST rather than GET despite being read-only: the request carries two\ncoordinate pairs, and a GET would put a rider's exact pickup and dropoff\ninto every access log and browser history along the way.",
      ),
  )
{}

export class SurgeApi extends HttpApi.make("SurgeApi")
  .annotate(OpenApi.Title, "trip.proto")
  .annotate(OpenApi.Version, "version not set")
  .add(PaymentsGroup, SimulatorGroup, TripsGroup)
{}
